#ifndef STRUCTS_H
#define STRUCTS_H

#define M_PI		3.14159265358979323846f	// matches value in gcc v2 math.h


struct vec4_t
{
    float x, y, z, w;

    vec4_t();
    ~vec4_t();
    vec4_t(float x, float y, float z, float w);
    vec4_t(float vec[4]);

    operator float* ();
};

enum human_cash_adjustment_reason : __int32
{
    HUMAN_CASH_ADJUSTMENT_ACTIVITY_REWARD = 0x0,
    HUMAN_CASH_ADJUSTMENT_CASH_INSTEAD_OF_RESEPECT = 0x1,
    HUMAN_CASH_ADJUSTMENT_CASH_PICKUP = 0x2,
    HUMAN_CASH_ADJUSTMENT_CHEATS = 0x3,
    HUMAN_CASH_ADJUSTMENT_CRIB_STASH = 0x4,
    HUMAN_CASH_ADJUSTMENT_DIVERSION_REWARD = 0x5,
    HUMAN_CASH_ADJUSTMENT_MISSION_REWARD = 0x6,
    HUMAN_CASH_ADJUSTMENT_PICKPOCKET = 0x7,
    HUMAN_CASH_ADJUSTMENT_UNLOCKABLE_LUMP_SUM = 0x8,
    HUMAN_CASH_ADJUSTMENT_HOMIE_DEATH = 0x9,
    HUMAN_CASH_ADJUSTMENT_PLAYER_DEATH = 0xA,
    HUMAN_CASH_ADJUSTMENT_PURCHASE = 0xB,
    HUMAN_CASH_ADJUSTMENT_DEBUG = 0xC,
    HUMAN_CASH_ADJUSTMENT_SCRIPTED = 0xD,
    NUM_HUMAN_CASH_ADJUSTMENT_REASONS = 0xE,
};

struct ctg_object_flags
{
    unsigned __int8 flagged_list_state;
    __int8 preserve_handle : 1;
    __int8 destruction_started : 1;
    __int8 destroyed : 1;
    __int8 active : 1;
    __int8 stub : 1;
};

struct object_handle
{
    unsigned __int64 m_data;
};

struct ctg_object 
{
    object_handle handle;
    object_handle parent;
    const char* obj_name;
    ctg_object* children;
    ctg_object* child_next;
    ctg_object* child_prev;
    ctg_object* flagged_next;
    ctg_object* flagged_prev;
    unsigned __int16 all_index;
    ctg_object_flags ctg_flags;
    unsigned __int8 m_derived_type;
};
struct v_mempool_base {};

enum gender_types : __int8
{
    GENDER_TYPE_MALE = 0x0,
    GENDER_TYPE_FEMALE = 0x1,
    NUM_GENDER_TYPES = 0x2,
    GENDER_TYPE_INVALID = 0x3,
};

struct rl_primitive_state
{
    unsigned int value;


    static rl_primitive_state* Singleton()
    {
        return ((rl_primitive_state*)(ResolveImport() + 0x12064D8));
    }
};


union __m128
{
    float m128_f32[4];
    unsigned __int64 m128_u64[2];
    char m128_i8[16];
    __int16 m128_i16[8];
    int m128_i32[4];
    __int64 m128_i64[2];
    unsigned __int8 m128_u8[16];
    unsigned __int16 m128_u16[8];
    unsigned int m128_u32[4];
};
struct vm_vector
{
    vm_vector() {}
    ~vm_vector() {}
    __m128 v;
};

struct vm_float
{
    __m128 v;
};

struct fl_vector
{
    float x;
    float y;
    float z;

    fl_vector();
    ~fl_vector();

    fl_vector(float x, float y, float z);
    fl_vector(float x, float y);
    fl_vector(float x);
    fl_vector(vm_vector val);

};
struct fl_matrix
{
    fl_vector rvec;
    fl_vector uvec;
    fl_vector fvec;
};


struct fl_matrix43
{
    fl_matrix43()
    {
    }
    ~fl_matrix43(){}

    fl_matrix m_rotation;
    fl_vector m_translation;
};

struct vm_matrix34
{
    vm_vector rows[3];
};

template<typename T>
struct base_array
{
    T* elt;
    int array_size;
    int num;
};

struct ctg_world
{
    char _0x00[0x8];
    ctg_object* m_current_flagged_object;
    unsigned __int8 m_current_flagged_mode;
    char level_name[65];
    unsigned __int8 m_num_game_types;
    volatile int m_thread_id;
    int m_max_world_objects;
    v_mempool_base* m_scratch_mempool;
    base_array<ctg_object*> m_all_objects;
    base_array<unsigned short> m_object_type_buckets[255];

    static ctg_world*& s_out_world()
    {
        return (*(ctg_world**)(ResolveImport() + 0x294C9B8));
    }
};


struct checksum_stri
{
    unsigned int checksum;
};

struct anim_bone
{
    char* name;
    fl_vector inv_translation;
    fl_vector rel_bone_translation;
    int parent_index;
    int vid;
};

struct anim_tag
{
    char* name;
    fl_matrix43 transformation;
    int parent_index;
    int vid;
};

struct anim_rig
{
    char name[32];
    unsigned int flags;
    int num_bones;
    int num_common_bones;
    int num_virtual_bones;
    int num_tags;
    unsigned int* bone_name_chksums;
    anim_bone* bones;
    anim_tag* tags;
    unsigned __int64 data_size;
    unsigned int uid;
    unsigned __int8* original_buffer;
};

struct character_info
{
    character_info* equivalency_next; 
    character_info* equivalency_prev; 
    const char* name;
    checksum_stri name_cs; 
    const char* model_name; 
    const char* morph_name;
    const char* csim_name; 
    const char* anim_set_name;
    const char* rig_name;
    anim_rig* character_rig;
    unsigned int m_default_personas[12];
    int num_associated_char_presets;
    void** associated_char_presets;
    int num_heads;
    void* heads;
    int num_general_props;
    void* general_props;
    float base_height;
    float default_height_scale;
    float height_scale_variation;
    float base_height_offset;
    float hit_sphere_size;
    float lod_distances[4];
    int gang_rank;
    gender_types gang_gender;
    char root_bone_index;
    char lower_spine_bone_index;
    char upper_spine_bone_index;
    char pelvis_bone_index;
    char head_bone_index;
    char neck_bone_index;
    char eye_l_bone_index;
    char eye_r_bone_index;
    char left_hip_bone_index;
    char left_knee_bone_index;
    char right_hip_bone_index;
    char right_knee_bone_index;
    char left_foot_bone_index;
    char left_toe_bone_index;
    char right_foot_bone_index;
    char right_toe_bone_index;
    char left_shoulder_bone_index;
    char left_elbow_bone_index;
    char right_shoulder_bone_index;
    char right_elbow_bone_index;
    char left_hand_bone_index;
    char right_hand_bone_index;
    char m_camera_root_offset_bone_index;
    char m_camera_animated_bone_index;
    char m_camera_fov_bone_index;
    char m_camera_dof_bone_index;
    __int16 left_equip_tag_index;
    __int16 right_equip_tag_index;
    __int16 left_forearm_equip_tag_index;
    __int16 right_forearm_equip_tag_index;
    __int16 human_shield_tag_index;
    __int16 human_shield_unarmed_tag_index;
    __int16 left_ik_node_bone_index;
    __int16 right_ik_node_bone_index;
    __int16 flame_breath_tag_index;
    void* left_hand_item;
    void* high_res_material;
    void* high_res_material_body;
    void* original_material_map_body;
    unsigned __int64 srid;
    unsigned __int64 high_res_srid;
    unsigned __int64 cin_res_srid;
    unsigned __int64 loaded_srid;

    unsigned __int32 initialized : 1;
    unsigned __int32 player_character : 1;
    unsigned __int32 high_res_texture_requested : 1;
    unsigned __int32 high_res_texture_loaded : 1;
    unsigned __int32 high_res_texture_request_unload : 1;
    unsigned __int32 debug_loaded : 1;
    unsigned __int32 heroic : 1;
};
struct v_animate {};
struct character_instance
{
    char _0x00[0x20];
    v_animate* vp;
    int aim_handle;
};

enum animation_state : uint32_t
{
    ANIM_STATE_INVALID = 0xFFFFFFFF,
    ANIM_ACTION_INVALID = 0xFFFFFFFF,
    ANIM_STATE_CUSTOM = 0x0,
    ANIM_STATE_NETWORK_TEST = 0x1,
    ANIM_STATE_STAND = 0x2,
    ANIM_STATE_STAND_READING_MAGAZINE = 0x3,
    ANIM_STATE_STAND_SMOKING_BLUNT = 0x4,
    ANIM_STATE_STAND_DRINKING_FORTY = 0x5,
    ANIM_STATE_DRUNK_STAND = 0x6,
    ANIM_STATE_CROUCH = 0x7,
    ANIM_STATE_CROUCH_WALK = 0x8,
    ANIM_STATE_SITTING = 0x9,
    ANIM_STATE_SLEEP = 0xA,
    ANIM_STATE_POSE = 0xB,
    ANIM_STATE_CAR_LEAN = 0xC,
    ANIM_STATE_COWER_STAND = 0xD,
    ANIM_STATE_COWER_STAND_VARIANT_1 = 0xE,
    ANIM_STATE_COWER_STAND_VARIANT_2 = 0xF,
    ANIM_STATE_COWER_STAND_VARIANT_3 = 0x10,
    ANIM_STATE_COWER_STAND_VARIANT_4 = 0x11,
    ANIM_STATE_ANGRY_STAND = 0x12,
    ANIM_STATE_SURRENDER_STAND = 0x13,
    ANIM_STATE_SURRENDER_WALK = 0x14,
    ANIM_STATE_REACTION_DEAD_BODY = 0x15,
    ANIM_STATE_REACTION_MELEE_STAND_AND_WATCH = 0x16,
    ANIM_STATE_REACTION_MELEE_STAND_AND_CHEER = 0x17,
    ANIM_STATE_REACTION_MELEE_STAND_AND_CHEER_2 = 0x18,
    ANIM_STATE_REACTION_MELEE_STAND_AND_CHEER_3 = 0x19,
    ANIM_STATE_WALK = 0x1A,
    ANIM_STATE_WALK_VARIANT_1 = 0x1B,
    ANIM_STATE_WALK_VARIANT_2 = 0x1C,
    ANIM_STATE_WALK_VARIANT_3 = 0x1D,
    ANIM_STATE_WALK_VARIANT_4 = 0x1E,
    ANIM_STATE_WALK_VARIANT_5 = 0x1F,
    ANIM_STATE_WALK_VARIANT_6 = 0x20,
    ANIM_STATE_WALK_VARIANT_7 = 0x21,
    ANIM_STATE_WALK_VARIANT_8 = 0x22,
    ANIM_STATE_WALK_VARIANT_9 = 0x23,
    ANIM_STATE_WALK_READING_MAGAZINE = 0x24,
    ANIM_STATE_WALK_SMOKING_BLUNT = 0x25,
    ANIM_STATE_WALK_DRINKING_FORTY = 0x26,
    ANIM_STATE_DRUNK_WALK = 0x27,
    ANIM_STATE_CUSTOM_WALK_MALE_2 = 0x28,
    ANIM_STATE_CUSTOM_WALK_FEMALE_1 = 0x29,
    ANIM_STATE_FLEE_WALK = 0x2A,
    ANIM_STATE_DRUNK_FLEE_WALK = 0x2B,
    ANIM_STATE_RUN = 0x2C,
    ANIM_STATE_RUN_VARIANT_1 = 0x2D,
    ANIM_STATE_RUN_VARIANT_2 = 0x2E,
    ANIM_STATE_RUN_VARIANT_3 = 0x2F,
    ANIM_STATE_DRUNK_RUN = 0x30,
    ANIM_STATE_RUN_STAND = 0x31,
    ANIM_STATE_SPRINT = 0x32,
    ANIM_STATE_SPRINT_READY = 0x33,
    ANIM_STATE_PIMP_SPRINT = 0x34,
    ANIM_STATE_WEAPON_SPRINT = 0x35,
    ANIM_STATE_COWER_RUN = 0x36,
    ANIM_STATE_COWER_RUN_VARIANT_1 = 0x37,
    ANIM_STATE_COWER_RUN_VARIANT_2 = 0x38,
    ANIM_STATE_COWER_RUN_VARIANT_3 = 0x39,
    ANIM_STATE_COWER_RUN_VARIANT_4 = 0x3A,
    ANIM_STATE_COWER_RUN_VARIANT_5 = 0x3B,
    ANIM_STATE_STAND_READY = 0x3C,
    ANIM_STATE_STAND_READY_LEFT = 0x3D,
    ANIM_STATE_STAND_READY_RIGHT = 0x3E,
    ANIM_STATE_STAND_READY_VARIANT_1 = 0x3F,
    ANIM_STATE_STAND_READY_VARIANT_2 = 0x40,
    ANIM_STATE_STAND_READY_VARIANT_3 = 0x41,
    ANIM_STATE_STAND_COVER_READY = 0x42,
    ANIM_STATE_STAND_AIM = 0x43,
    ANIM_STATE_STAND_AIM_OVER = 0x44,
    ANIM_STATE_STAND_DOWN_READY = 0x45,
    ANIM_STATE_WALK_AIM = 0x46,
    ANIM_STATE_WALK_AIM_BACK = 0x47,
    ANIM_STATE_WALK_AIM_LEFT = 0x48,
    ANIM_STATE_WALK_AIM_RIGHT = 0x49,
    ANIM_STATE_WALK_AIM_LH = 0x4A,
    ANIM_STATE_WALK_AIM_BACK_LH = 0x4B,
    ANIM_STATE_WALK_AIM_LEFT_LH = 0x4C,
    ANIM_STATE_WALK_AIM_RIGHT_LH = 0x4D,
    ANIM_STATE_RUN_AIM = 0x4E,
    ANIM_STATE_RUN_AIM_BACK = 0x4F,
    ANIM_STATE_RUN_AIM_LEFT = 0x50,
    ANIM_STATE_RUN_AIM_RIGHT = 0x51,
    ANIM_STATE_BACKPEDAL_AIM_LEFT = 0x52,
    ANIM_STATE_BACKPEDAL_AIM_RIGHT = 0x53,
    ANIM_STATE_BACKPEDAL_AIM_BACK_LEFT = 0x54,
    ANIM_STATE_BACKPEDAL_AIM_BACK_RIGHT = 0x55,
    ANIM_STATE_RUN_AIM_LH = 0x56,
    ANIM_STATE_RUN_AIM_BACK_LH = 0x57,
    ANIM_STATE_CROUCH_AIM = 0x58,
    ANIM_STATE_CROUCH_WALK_AIM = 0x59,
    ANIM_STATE_CROUCH_WALK_AIM_BACK = 0x5A,
    ANIM_STATE_CROUCH_WALK_AIM_LEFT = 0x5B,
    ANIM_STATE_CROUCH_WALK_AIM_RIGHT = 0x5C,
    ANIM_STATE_WALK_LEFT = 0x5D,
    ANIM_STATE_WALK_RIGHT = 0x5E,
    ANIM_STATE_WALK_BACK = 0x5F,
    ANIM_STATE_WALK_READY = 0x60,
    ANIM_STATE_WALK_READY_LEFT = 0x61,
    ANIM_STATE_WALK_READY_RIGHT = 0x62,
    ANIM_STATE_WALK_READY_BACK_RIGHT = 0x63,
    ANIM_STATE_WALK_READY_BACK = 0x64,
    ANIM_STATE_WALK_READY_BACK_LEFT = 0x65,
    ANIM_STATE_WALK_DOWN_READY = 0x66,
    ANIM_STATE_RUN_LEFT = 0x67,
    ANIM_STATE_RUN_RIGHT = 0x68,
    ANIM_STATE_RUN_BACK = 0x69,
    ANIM_STATE_RUN_READY = 0x6A,
    ANIM_STATE_RUN_READY_LEFT = 0x6B,
    ANIM_STATE_RUN_READY_RIGHT = 0x6C,
    ANIM_STATE_RUN_READY_BACK_RIGHT = 0x6D,
    ANIM_STATE_RUN_READY_BACK = 0x6E,
    ANIM_STATE_RUN_READY_BACK_LEFT = 0x6F,
    ANIM_STATE_CROUCH_WALK_LEFT = 0x70,
    ANIM_STATE_CROUCH_WALK_RIGHT = 0x71,
    ANIM_STATE_CROUCH_WALK_BACK = 0x72,
    ANIM_STATE_CROUCH_READY = 0x73,
    ANIM_STATE_CROUCH_WALK_READY_FWD = 0x74,
    ANIM_STATE_CROUCH_WALK_READY_LEFT = 0x75,
    ANIM_STATE_CROUCH_WALK_READY_RIGHT = 0x76,
    ANIM_STATE_CROUCH_WALK_READY_BACK_RIGHT = 0x77,
    ANIM_STATE_CROUCH_WALK_READY_BACK = 0x78,
    ANIM_STATE_CROUCH_WALK_READY_BACK_LEFT = 0x79,
    ANIM_STATE_CROUCH_WARY = 0x7A,
    ANIM_STATE_FINE_AIM_WALK = 0x7B,
    ANIM_STATE_FINE_AIM_STAND = 0x7C,
    ANIM_STATE_DBNO_SUFFER = 0x7D,
    ANIM_STATE_DBNO_SUFFER_MARS_KILLBANE = 0x7E,
    ANIM_STATE_DBNO_MARS_HOMIE_DEATH = 0x7F,
    ANIM_STATE_STAND_SHLDR_READY = 0x80,
    ANIM_STATE_WALK_SHLDR_READY = 0x81,
    ANIM_STATE_CALM_FALL = 0x82,
    ANIM_STATE_CALM_FALL_RUN = 0x83,
    ANIM_STATE_PANIC_FALL = 0x84,
    ANIM_STATE_CANNONBALL_FALL = 0x85,
    ANIM_STATE_BK_LIEDOWN = 0x86,
    ANIM_STATE_FWD_LIEDOWN = 0x87,
    ANIM_STATE_SWIM_TREAD = 0x88,
    ANIM_STATE_SWIM = 0x89,
    ANIM_STATE_SWIM_SURFACE = 0x8A,
    ANIM_STATE_PANT = 0x8B,
    ANIM_STATE_CONSTRUCTION_JACKHAMMER = 0x8C,
    ANIM_STATE_HEAD_COVER_WALK = 0x8D,
    ANIM_STATE_HEAD_COVER_STAND = 0x8E,
    ANIM_STATE_HEAD_COVER_RUN = 0x8F,
    ANIM_STATE_PHONE_CALL_TALK = 0x90,
    ANIM_STATE_UMBRELLA_WALK = 0x91,
    ANIM_STATE_UMBRELLA_STAND = 0x92,
    ANIM_STATE_UMBRELLA_RUN = 0x93,
    ANIM_STATE_SHOPPING_BAG_WALK = 0x94,
    ANIM_STATE_SUITCASE_WALK = 0x95,
    ANIM_STATE_PROTEST_STAND = 0x96,
    ANIM_STATE_GURNEY_SLEEP_A = 0x97,
    ANIM_STATE_GURNEY_SLEEP_B = 0x98,
    ANIM_STATE_MP_CROUCH_EAT = 0x99,
    ANIM_STATE_CELL_STAND = 0x9A,
    ANIM_STATE_CELL_WALK = 0x9B,
    ANIM_STATE_CELL_RUN = 0x9C,
    ANIM_STATE_CELL_CROUCH = 0x9D,
    ANIM_STATE_CELL_CROUCH_WALK = 0x9E,
    ANIM_STATE_CELL_TXT_STAND = 0x9F,
    ANIM_STATE_CELL_TXT_WALK = 0xA0,
    ANIM_STATE_CELL_TXT_RUN = 0xA1,
    ANIM_STATE_CELL_TXT_CROUCH = 0xA2,
    ANIM_STATE_CELL_TXT_CROUCH_WALK = 0xA3,
    ANIM_STATE_ZOMBIE_EAT = 0xA4,
    ANIM_STATE_ZOMBIE_GRAB_A = 0xA5,
    ANIM_STATE_ZOMBIE_GRAB_A_VICTIM = 0xA6,
    ANIM_STATE_ZOMBIE_GRAB_B = 0xA7,
    ANIM_STATE_ZOMBIE_GRAB_B_VICTIM = 0xA8,
    ANIM_STATE_HS_STAND = 0xA9,
    ANIM_STATE_HS_WALK_FORWARD = 0xAA,
    ANIM_STATE_HS_WALK_BACK = 0xAB,
    ANIM_STATE_HS_WALK_LEFT = 0xAC,
    ANIM_STATE_HS_WALK_RIGHT = 0xAD,
    ANIM_STATE_HS_RUN_FORWARD = 0xAE,
    ANIM_STATE_HS_RUN_BACK = 0xAF,
    ANIM_STATE_HS_RUN_LEFT = 0xB0,
    ANIM_STATE_HS_RUN_RIGHT = 0xB1,
    ANIM_STATE_HS_VICTIM_STAND = 0xB2,
    ANIM_STATE_HS_VICTIM_WALK_FORWARD = 0xB3,
    ANIM_STATE_HS_VICTIM_WALK_BACK = 0xB4,
    ANIM_STATE_HS_VICTIM_WALK_LEFT = 0xB5,
    ANIM_STATE_HS_VICTIM_WALK_RIGHT = 0xB6,
    ANIM_STATE_HS_VICTIM_RUN_FORWARD = 0xB7,
    ANIM_STATE_HS_VICTIM_RUN_BACK = 0xB8,
    ANIM_STATE_HS_VICTIM_RUN_LEFT = 0xB9,
    ANIM_STATE_HS_VICTIM_RUN_RIGHT = 0xBA,
    ANIM_STATE_HS_BRUTE_VICTIM_WALK_FORWARD = 0xBB,
    ANIM_STATE_OS_STAND = 0xBC,
    ANIM_STATE_OS_WALK_FORWARD = 0xBD,
    ANIM_STATE_OS_WALK_BACK = 0xBE,
    ANIM_STATE_OS_WALK_LEFT = 0xBF,
    ANIM_STATE_OS_WALK_RIGHT = 0xC0,
    ANIM_STATE_OS_RUN_FORWARD = 0xC1,
    ANIM_STATE_OS_RUN_BACK = 0xC2,
    ANIM_STATE_OS_RUN_LEFT = 0xC3,
    ANIM_STATE_OS_RUN_RIGHT = 0xC4,
    ANIM_STATE_OS_VICTIM_STAND = 0xC5,
    ANIM_STATE_OS_VICTIM_WALK_FORWARD = 0xC6,
    ANIM_STATE_OS_VICTIM_WALK_BACK = 0xC7,
    ANIM_STATE_OS_VICTIM_WALK_LEFT = 0xC8,
    ANIM_STATE_OS_VICTIM_WALK_RIGHT = 0xC9,
    ANIM_STATE_OS_VICTIM_RUN_FORWARD = 0xCA,
    ANIM_STATE_OS_VICTIM_RUN_BACK = 0xCB,
    ANIM_STATE_OS_VICTIM_RUN_LEFT = 0xCC,
    ANIM_STATE_OS_VICTIM_RUN_RIGHT = 0xCD,
    ANIM_STATE_FLASHING_OPEN_STAND = 0xCE,
    ANIM_STATE_STREAKING_STAND = 0xCF,
    ANIM_STATE_STREAKING_RUN = 0xD0,
    ANIM_STATE_STREAKING_SPRINT = 0xD1,
    ANIM_STATE_HOSE_STAND = 0xD2,
    ANIM_STATE_HOSE_SPRAYED = 0xD3,
    ANIM_STATE_ATHLETE_STAND = 0xD4,
    ANIM_STATE_MOVIESTAR_STAND = 0xD5,
    ANIM_STATE_MUSICIAN_STAND = 0xD6,
    ANIM_STATE_PORNSTAR_STAND = 0xD7,
    ANIM_STATE_ATHLETE_WALK = 0xD8,
    ANIM_STATE_MOVIESTAR_WALK = 0xD9,
    ANIM_STATE_MUSICIAN_WALK = 0xDA,
    ANIM_STATE_PORNSTAR_WALK = 0xDB,
    ANIM_STATE_ARREST_CUFFED = 0xDC,
    ANIM_STATE_VEHICLE_SURF_STAND_NETWORK = 0xDD,
    ANIM_STATE_VEHICLE_SURF_HANDSTAND_NETWORK = 0xDE,
    ANIM_STATE_FINISH1_A = 0xDF,
    ANIM_STATE_FINISH1_B = 0xE0,
    ANIM_STATE_FINISH2_A = 0xE1,
    ANIM_STATE_FINISH2_B = 0xE2,
    ANIM_STATE_FINISH3_A = 0xE3,
    ANIM_STATE_FINISH3_B = 0xE4,
    ANIM_STATE_FINISH2_1_A = 0xE5,
    ANIM_STATE_FINISH2_1_B = 0xE6,
    ANIM_STATE_FINISH2_2_A = 0xE7,
    ANIM_STATE_FINISH2_2_B = 0xE8,
    ANIM_STATE_FINISH2_3_A = 0xE9,
    ANIM_STATE_FINISH2_3_B = 0xEA,
    ANIM_STATE_GRAPPLE_HOLD = 0xEB,
    ANIM_STATE_GRAPPLE_HOLD_VICTIM = 0xEC,
    ANIM_STATE_FUZZ_PURSE_SNATCH_STAND = 0xED,
    ANIM_STATE_FUZZ_PURSE_SNATCH_WALK = 0xEE,
    ANIM_STATE_FUZZ_PURSE_SNATCH_RUN = 0xEF,
    ANIM_STATE_ATTACK_STAND = 0xF0,
    ANIM_STATE_ATTACK_WALK = 0xF1,
    ANIM_STATE_ATTACK_RUN = 0xF2,
    ANIM_STATE_FACE_ANGRY = 0xF3,
    ANIM_STATE_FACE_DISGUSTED = 0xF4,
    ANIM_STATE_FACE_EVIL = 0xF5,
    ANIM_STATE_FACE_FEARFUL = 0xF6,
    ANIM_STATE_FACE_GRUMPY = 0xF7,
    ANIM_STATE_FACE_HAPPY = 0xF8,
    ANIM_STATE_FACE_INEBRIATED = 0xF9,
    ANIM_STATE_FACE_JOYFUL = 0xFA,
    ANIM_STATE_FACE_MELLOW = 0xFB,
    ANIM_STATE_FACE_PAIN = 0xFC,
    ANIM_STATE_FACE_SAD = 0xFD,
    ANIM_STATE_FACE_SCARED = 0xFE,
    ANIM_STATE_FACE_SMARMY = 0xFF,
    ANIM_STATE_FACE_SNEER = 0x100,
    ANIM_STATE_FACE_SURPRISED = 0x101,
    ANIM_STATE_FACE_BLANK = 0x102,
    ANIM_STATE_FACE_ROGUISH = 0x103,
    ANIM_STATE_FACE_AIM = 0x104,
    ANIM_STATE_HELI_RIDE_RIGHT_FLOOR = 0x105,
    ANIM_STATE_HELI_RIDE_RIGHT_SEAT = 0x106,
    ANIM_STATE_HELI_RIDE_LEFT_FLOOR = 0x107,
    ANIM_STATE_HELI_RIDE_LEFT_SEAT = 0x108,
    ANIM_STATE_HELI_RIDE_RIGHT_COOP_A = 0x109,
    ANIM_STATE_HELI_RIDE_RIGHT_COOP_B = 0x10A,
    ANIM_STATE_HELI_RIDE_RIGHT_COOP_C = 0x10B,
    ANIM_STATE_DRIVE_FORWARD = 0x10C,
    ANIM_STATE_DRIVE_REVERSE = 0x10D,
    ANIM_STATE_DRIVE_STOPPED = 0x10E,
    ANIM_STATE_DRIVE_FORWARD_FAST = 0x10F,
    ANIM_STATE_DRIVE_FORWARD_TURN_LEFT = 0x110,
    ANIM_STATE_DRIVE_FORWARD_TURN_RIGHT = 0x111,
    ANIM_STATE_DRIVE_REVERSE_TURN_LEFT = 0x112,
    ANIM_STATE_DRIVE_REVERSE_TURN_RIGHT = 0x113,
    ANIM_STATE_RIDE = 0x114,
    ANIM_STATE_RIDE_LEFT = 0x115,
    ANIM_STATE_RIDE_LEFT_BACK = 0x116,
    ANIM_STATE_RIDE_RIGHT = 0x117,
    ANIM_STATE_RIDE_RIGHT_BACK = 0x118,
    ANIM_STATE_RIDE_RIGHT_HOSTAGE_1 = 0x119,
    ANIM_STATE_RIDE_LEFT_HOSTAGE_1 = 0x11A,
    ANIM_STATE_DRIVE_FORWARD_READY = 0x11B,
    ANIM_STATE_DRIVE_FORWARD_READY_LEFT = 0x11C,
    ANIM_STATE_DRIVE_FORWARD_READY_RIGHT = 0x11D,
    ANIM_STATE_DRIVE_FORWARD_READY_BACK = 0x11E,
    ANIM_STATE_DRIVE_FORWARD_READY_ALT = 0x11F,
    ANIM_STATE_DRIVE_FORWARD_READY_LEFT_ALT = 0x120,
    ANIM_STATE_DRIVE_FORWARD_READY_RIGHT_ALT = 0x121,
    ANIM_STATE_DRIVE_FORWARD_READY_BACK_ALT = 0x122,
    ANIM_STATE_DRIVE_WINDOW_LEFT_READY_RIGHT = 0x123,
    ANIM_STATE_DRIVE_FORWARD_TURN_LEFT_READY = 0x124,
    ANIM_STATE_DRIVE_FORWARD_TURN_LEFT_READY_LEFT = 0x125,
    ANIM_STATE_DRIVE_FORWARD_TURN_LEFT_READY_RIGHT = 0x126,
    ANIM_STATE_DRIVE_FORWARD_TURN_LEFT_READY_BACK = 0x127,
    ANIM_STATE_DRIVE_FORWARD_TURN_RIGHT_READY = 0x128,
    ANIM_STATE_DRIVE_FORWARD_TURN_RIGHT_READY_LEFT = 0x129,
    ANIM_STATE_DRIVE_FORWARD_TURN_RIGHT_READY_RIGHT = 0x12A,
    ANIM_STATE_DRIVE_FORWARD_TURN_RIGHT_READY_BACK = 0x12B,
    ANIM_STATE_RIDE_READY_FORWARD = 0x12C,
    ANIM_STATE_RIDE_READY_LEFT = 0x12D,
    ANIM_STATE_RIDE_READY_RIGHT = 0x12E,
    ANIM_STATE_RIDE_READY_BACK = 0x12F,
    ANIM_STATE_WINDOW_LEFT_READY_RIGHT = 0x130,
    ANIM_STATE_WINDOW_RIGHT_READY_LEFT = 0x131,
    ANIM_STATE_RIDE_RIGHT_READY = 0x132,
    ANIM_STATE_RIDE_RIGHT_READY_LEFT = 0x133,
    ANIM_STATE_RIDE_RIGHT_READY_RIGHT = 0x134,
    ANIM_STATE_RIDE_RIGHT_READY_BACK = 0x135,
    ANIM_STATE_RIDE_RIGHTBACK_READY = 0x136,
    ANIM_STATE_RIDE_RIGHTBACK_READY_LEFT = 0x137,
    ANIM_STATE_RIDE_RIGHTBACK_READY_RIGHT = 0x138,
    ANIM_STATE_RIDE_RIGHTBACK_READY_BACK = 0x139,
    ANIM_STATE_RIDE_LEFT_READY = 0x13A,
    ANIM_STATE_RIDE_LEFT_READY_LEFT = 0x13B,
    ANIM_STATE_RIDE_LEFT_READY_RIGHT = 0x13C,
    ANIM_STATE_RIDE_LEFT_READY_BACK = 0x13D,
    ANIM_STATE_RIDE_LEFTBACK_READY = 0x13E,
    ANIM_STATE_RIDE_LEFTBACK_READY_LEFT = 0x13F,
    ANIM_STATE_RIDE_LEFTBACK_READY_RIGHT = 0x140,
    ANIM_STATE_RIDE_LEFTBACK_READY_BACK = 0x141,
    ANIM_STATE_RIOT_RIDE_LEFT = 0x142,
    ANIM_STATE_RIOT_RIDE_RIGHT = 0x143,
    ANIM_STATE_TANK_TURRET_RIDE = 0x144,
    ANIM_STATE_BRUTE_AUTO_RIDE = 0x145,
    ANIM_STATE_ROLLERBLADER_RIDE_LEFT = 0x146,
    ANIM_STATE_ROLLERBLADER_RIDE_RIGHT = 0x147,
    ANIM_STATE_CPR_CROUCH_STATE_1 = 0x148,
    ANIM_STATE_CPR_CROUCH_STATE_2 = 0x149,
    ANIM_STATE_CPR_LIEDOWN = 0x14A,
    ANIM_STATE_CPR_CROUCH_PRESSING = 0x14B,
    ANIM_STATE_DEFIB_CROUCH_CHARGE_LEFT = 0x14C,
    ANIM_STATE_DEFIB_CROUCH_CHARGE_RIGHT = 0x14D,
    ANIM_STATE_DEFIB_CROUCH_CHARGING = 0x14E,
    ANIM_STATE_DEFIB_FLINCH_BACK = 0x14F,
    ANIM_STATE_FIRING = 0x150,
    ANIM_STATE_FREE_FALL_NETWORK = 0x151,
    ANIM_STATE_RAPPEL_FALL = 0x152,
    ANIM_STATE_POWER_ATTACK_PREP_LEFT = 0x153,
    ANIM_STATE_POWER_ATTACK_PREP_RIGHT = 0x154,
    ANIM_STATE_GAT_INJURED = 0x155,
    ANIM_STATE_GANG_CUST_STAND_MALE_A = 0x156,
    ANIM_STATE_GANG_CUST_STAND_MALE_B = 0x157,
    ANIM_STATE_GANG_CUST_STAND_FEMALE_A = 0x158,
    ANIM_STATE_GANG_CUST_STAND_FEMALE_B = 0x159,
    ANIM_STATE_PLAYER_COVER_STAND_LEFT = 0x15A,
    ANIM_STATE_PLAYER_COVER_CROUCH = 0x15B,
    ANIM_STATE_PLAYER_COVER_CROUCH_AIM_FORWARD = 0x15C,
    ANIM_STATE_COVER_STAND = 0x15D,
    ANIM_STATE_COVER_CROUCH = 0x15E,
    ANIM_STATE_SKATE_GLIDE_LEFT = 0x15F,
    ANIM_STATE_SKATE_GLIDE_RIGHT = 0x160,
    ANIM_STATE_WALLSTOP = 0x161,
    ANIM_STATE_WALK_INVESTIGATE = 0x162,
    ANIM_STATE_FALLING = 0x163,
    ANIM_STATE_MAN_CANNONED = 0x164,
    ANIM_STATE_SKYDIVING = 0x165,
    ANIM_STATE_SKYDIVING_DIVE = 0x166,
    ANIM_STATE_SKYDIVING_UPSIDE_DOWN = 0x167,
    ANIM_STATE_SKYDIVING_SHIELD_UPSIDE_DOWN = 0x168,
    ANIM_STATE_SKYDIVING_HOLD_PARACHUTE = 0x169,
    ANIM_STATE_SKYDIVING_PARACHUTE_SHOOT = 0x16A,
    ANIM_STATE_SKYDIVING_NON_COMBAT_DIVE_NPC = 0x16B,
    ANIM_STATE_SKYDIVING_NON_COMBAT_DIVE_PLAYER = 0x16C,
    ANIM_STATE_SKYDIVING_PANIC_FALL = 0x16D,
    ANIM_STATE_SKYDIVING_COVER = 0x16E,
    ANIM_STATE_SKYDIVING_COVER_FIRE = 0x16F,
    ANIM_STATE_SKYDIVING_CHUTE = 0x170,
    ANIM_STATE_SKYDIVING_CHUTE_DEAD = 0x171,
    ANIM_STATE_RIDING_KILLBANE = 0x172,
    ANIM_STATE_CHOKE_OUT_KILLBANE = 0x173,
    ANIM_STATE_JUMP_NETWORK = 0x174,
    ANIM_STATE_CLIMB_NETWORK = 0x175,
    ANIM_STATE_PLAYER_NETWORK = 0x176,
    ANIM_STATE_AIM_NETWORK = 0x177,
    ANIM_STATE_AIM_NETWORK_FORWARD_RIGHT = 0x178,
    ANIM_STATE_AIM_NETWORK_BACKPEDAL_RIGHT = 0x179,
    ANIM_STATE_AIM_NETWORK_FORWARD_LEFT = 0x17A,
    ANIM_STATE_AIM_NETWORK_BACKPEDAL_LEFT = 0x17B,
    ANIM_STATE_AIM_NETWORK_STAND = 0x17C,
    ANIM_STATE_AIM_NETWORK_FORWARD_CROUCH = 0x17D,
    ANIM_STATE_AIM_NETWORK_BACKPEDAL_CROUCH = 0x17E,
    ANIM_STATE_AIM_NETWORK_CROUCH = 0x17F,
    ANIM_STATE_AIM_NETWORK_RELOAD = 0x180,
    ANIM_STATE_DRIVE_NETWORK = 0x181,
    ANIM_STATE_DRIVE_READY_NETWORK = 0x182,
    ANIM_STATE_RIDE_NETWORK = 0x183,
    ANIM_STATE_RIDE_READY_NETWORK = 0x184,
    ANIM_STATE_RIDE_LEFT_NETWORK = 0x185,
    ANIM_STATE_RIDE_RIGHT_NETWORK = 0x186,
    ANIM_STATE_RIDE_PONY_CART_DRIVE_NETWORK = 0x187,
    ANIM_STATE_RIDE_PONY_CART_RIDE_LEFT_NETWORK = 0x188,
    ANIM_STATE_RIDE_PONY_CART_RIDE_RIGHT_NETWORK = 0x189,
    ANIM_STATE_HELI_RIDE_LEFT_FLOOR_NETWORK = 0x18A,
    ANIM_STATE_HELI_RIDE_RIGHT_FLOOR_NETWORK = 0x18B,
    ANIM_STATE_RIOT_RIDE_LEFT_NETWORK = 0x18C,
    ANIM_STATE_RIOT_RIDE_RIGHT_NETWORK = 0x18D,
    ANIM_STATE_TANK_TURRET_RIDE_NETWORK = 0x18E,
    ANIM_STATE_RIDE_RIGHT_INSIDE_NETWORK = 0x18F,
    ANIM_STATE_RIDE_LEFT_INSIDE_NETWORK = 0x190,
    ANIM_STATE_BRUTE_TRUCK_NETWORK = 0x191,
    ANIM_STATE_BALL_HANG_HOST_NETWORK = 0x192,
    ANIM_STATE_BALL_HANG_CLIENT_NETWORK = 0x193,
    ANIM_STATE_HELI_STAND_NETWORK = 0x194,
    ANIM_STATE_HELI_STAND_02_NETWORK = 0x195,
    ANIM_STATE_HELI_STAND_03_NETWORK = 0x196,
    ANIM_STATE_HELI_STAND_04_NETWORK = 0x197,
    ANIM_STATE_HELI_STAND_13_NETWORK = 0x198,
    ANIM_STATE_ROLLERBLADER_RIDE_LEFT_NETWORK = 0x199,
    ANIM_STATE_ROLLERBLADER_RIDE_RIGHT_NETWORK = 0x19A,
    ANIM_STATE_RUN_ON_FIRE = 0x19B,
    ANIM_STATE_RUN_ON_FIRE_VARIANT_1 = 0x19C,
    ANIM_STATE_RHAMMER_CLOSED = 0x19D,
    ANIM_STATE_RHAMMER_OPEN = 0x19E,
    ANIM_STATE_PRED_COMPUTER_CLOSED = 0x19F,
    ANIM_STATE_PRED_COMPUTER_CROUCH_OPENED = 0x1A0,
    ANIM_STATE_PRED_COMPUTER_STAND_OPENED = 0x1A1,
    ANIM_STATE_RC_CROUCH_USE = 0x1A2,
    ANIM_STATE_RC_STAND_USE = 0x1A3,
    ANIM_STATE_DASH_A = 0x1A4,
    ANIM_STATE_DASH_B = 0x1A5,
    ANIM_STATE_DASH_C = 0x1A6,
    ANIM_STATE_OBSERVE_1 = 0x1A7,
    ANIM_STATE_OBSERVE_2 = 0x1A8,
    ANIM_STATE_OBSERVE_3 = 0x1A9,
    ANIM_STATE_OBSERVE_4 = 0x1AA,
    ANIM_STATE_OBSERVE_5 = 0x1AB,
    ANIM_STATE_STAND_GA = 0x1AC,
    ANIM_STATE_FLASHBANG_A = 0x1AD,
    ANIM_STATE_FLASHBANG_B = 0x1AE,
    ANIM_STATE_FLASHBANG_C = 0x1AF,
    ANIM_STATE_FLASHBANG_D = 0x1B0,
    ANIM_STATE_CUST_STAND_M = 0x1B1,
    ANIM_STATE_CUST_STAND_BACKPACK_M = 0x1B2,
    ANIM_STATE_CUST_STAND_LOWER_M = 0x1B3,
    ANIM_STATE_CUST_STAND_UPPER_M = 0x1B4,
    ANIM_STATE_CUST_STAND_WRIST_M = 0x1B5,
    ANIM_STATE_CUST_STAND_FEET_M = 0x1B6,
    ANIM_STATE_CUST_STAND_F = 0x1B7,
    ANIM_STATE_CUST_STAND_BACKPACK_F = 0x1B8,
    ANIM_STATE_CUST_STAND_LOWER_F = 0x1B9,
    ANIM_STATE_CUST_STAND_UPPER_F = 0x1BA,
    ANIM_STATE_CUST_STAND_WRIST_F = 0x1BB,
    ANIM_STATE_CUST_STAND_FEET_F = 0x1BC,
    ANIM_STATE_M01_Z01_STAND = 0x1BD,
    ANIM_STATE_ESCORT_TIGER_CALM = 0x1BE,
    ANIM_STATE_ESCORT_DRIVER_CALM = 0x1BF,
    ANIM_STATE_ESCORT_PASSENGER_CALM = 0x1C0,
    ANIM_STATE_ESCORT_PASSENGER_CALMING_TIGER = 0x1C1,
    ANIM_STATE_ESCORT_TIGER_RAGING_A = 0x1C2,
    ANIM_STATE_ESCORT_TIGER_RAGING_B = 0x1C3,
    ANIM_STATE_ESCORT_TIGER_PETTING_A = 0x1C4,
    ANIM_STATE_ESCORT_TIGER_PETTING_B = 0x1C5,
    ANIM_STATE_FIAJ_A = 0x1C6,
    ANIM_STATE_FIAJ_B = 0x1C7,
    ANIM_STATE_FIAJ_C = 0x1C8,
    ANIM_STATE_FIAJ_D = 0x1C9,
    ANIM_STATE_FIAJ_E = 0x1CA,
    ANIM_STATE_FIAJ_F = 0x1CB,
    ANIM_STATE_WOUNDED_CHEST_STAND = 0x1CC,
    ANIM_STATE_WOUNDED_CHEST_WALK = 0x1CD,
    ANIM_STATE_FLYING = 0x1CE,
    ANIM_STATE_STUCK = 0x1CF,
    ANIM_STATE_UMBRELLA_OPEN = 0x1D0,
    ANIM_STATE_CHARGED = 0x1D1,
    ANIM_STATE_MINIGUN_FIRING = 0x1D2,
    ANIM_ACTION_CUSTOM = 0x1D3,
    ANIM_ACTION_IDLE = 0x1D4,
    ANIM_ACTION_IDLE_VARIANT_1 = 0x1D5,
    ANIM_ACTION_IDLE_VARIANT_2 = 0x1D6,
    ANIM_ACTION_IDLE_VARIANT_3 = 0x1D7,
    ANIM_ACTION_IDLE_VARIANT_4 = 0x1D8,
    ANIM_ACTION_IDLE_VARIANT_5 = 0x1D9,
    ANIM_ACTION_IDLE_VARIANT_6 = 0x1DA,
    ANIM_ACTION_IDLE_VARIANT_7 = 0x1DB,
    ANIM_ACTION_IDLE_VARIANT_8 = 0x1DC,
    ANIM_ACTION_IDLE_ADJUST_CROTCH = 0x1DD,
    ANIM_ACTION_IDLE_ADJUST_CROTCH_MOVE = 0x1DE,
    ANIM_ACTION_IDLE_EAT_DONUT = 0x1DF,
    ANIM_ACTION_IDLE_FIX_HAIR = 0x1E0,
    ANIM_ACTION_IDLE_FLIRT = 0x1E1,
    ANIM_ACTION_IDLE_GREET = 0x1E2,
    ANIM_ACTION_IDLE_GREET_MOVE = 0x1E3,
    ANIM_ACTION_IDLE_LOOK_NAILS = 0x1E4,
    ANIM_ACTION_IDLE_SCRATCH_ASS = 0x1E5,
    ANIM_ACTION_IDLE_SCRATCH_ASS_MOVE = 0x1E6,
    ANIM_ACTION_IDLE_SHOWCASE = 0x1E7,
    ANIM_ACTION_IDLE_STRETCHING = 0x1E8,
    ANIM_ACTION_IDLE_SUCKER = 0x1E9,
    ANIM_ACTION_IDLE_TIE_SHOE = 0x1EA,
    ANIM_ACTION_IDLE_TOUCH_SELF = 0x1EB,
    ANIM_ACTION_IDLE_TWIRL_HAIR = 0x1EC,
    ANIM_ACTION_IDLE_MOVE_VARIANT_1 = 0x1ED,
    ANIM_ACTION_IDLE_MOVE_VARIANT_2 = 0x1EE,
    ANIM_ACTION_IDLE_MOVE_VARIANT_3 = 0x1EF,
    ANIM_ACTION_IDLE_MOVE_VARIANT_4 = 0x1F0,
    ANIM_ACTION_IDLE_MOVE_VARIANT_5 = 0x1F1,
    ANIM_ACTION_IDLE_MOVE_VARIANT_6 = 0x1F2,
    ANIM_ACTION_IDLE_MOVE_VARIANT_7 = 0x1F3,
    ANIM_ACTION_SIT_TO_STAND = 0x1F4,
    ANIM_ACTION_SIT_TO_STAND_STARTLE = 0x1F5,
    ANIM_ACTION_EQUIP = 0x1F6,
    ANIM_ACTION_EQUIP_HUMAN_SHIELD = 0x1F7,
    ANIM_ACTION_LAND_SOFT = 0x1F8,
    ANIM_ACTION_LAND_MEDIUM = 0x1F9,
    ANIM_ACTION_LAND_HARD = 0x1FA,
    ANIM_ACTION_STAND_SHUFFLE_RIGHT = 0x1FB,
    ANIM_ACTION_STAND_SHUFFLE_LEFT = 0x1FC,
    ANIM_ACTION_STAND_READY_SHUFFLE_RIGHT = 0x1FD,
    ANIM_ACTION_STAND_READY_SHUFFLE_LEFT = 0x1FE,
    ANIM_ACTION_CROUCH_SHUFFLE_RIGHT = 0x1FF,
    ANIM_ACTION_CROUCH_SHUFFLE_LEFT = 0x200,
    ANIM_ACTION_CROUCH_READY_SHUFFLE_RIGHT = 0x201,
    ANIM_ACTION_CROUCH_READY_SHUFFLE_LEFT = 0x202,
    ANIM_ACTION_DODGE_LEFT = 0x203,
    ANIM_ACTION_DODGE_LEFT_1 = 0x204,
    ANIM_ACTION_DODGE_LEFT_2 = 0x205,
    ANIM_ACTION_DODGE_RIGHT = 0x206,
    ANIM_ACTION_DODGE_RIGHT_1 = 0x207,
    ANIM_ACTION_DODGE_RIGHT_2 = 0x208,
    ANIM_ACTION_DIVE = 0x209,
    ANIM_ACTION_DIVE_LEFT = 0x20A,
    ANIM_ACTION_DIVE_RIGHT = 0x20B,
    ANIM_ACTION_DRUNK_STUMBLE = 0x20C,
    ANIM_ACTION_COWER_RUN_FALL = 0x20D,
    ANIM_ACTION_COWER_RUN_FALL_VARIANT_1 = 0x20E,
    ANIM_ACTION_COWER_RUN_FALL_VARIANT_2 = 0x20F,
    ANIM_ACTION_COWER_COMBAT = 0x210,
    ANIM_ACTION_COWER_TO_STAND = 0x211,
    ANIM_ACTION_COWER_TO_STAND_VARIANT_1 = 0x212,
    ANIM_ACTION_COWER_TO_STAND_VARIANT_2 = 0x213,
    ANIM_ACTION_COWER_TO_STAND_VARIANT_3 = 0x214,
    ANIM_ACTION_COWER_TO_STAND_VARIANT_4 = 0x215,
    ANIM_ACTION_COWER_TO_STAND_FAST_VARIANT_1 = 0x216,
    ANIM_ACTION_COWER_TO_STAND_FAST_VARIANT_2 = 0x217,
    ANIM_ACTION_COWER_TO_STAND_FAST_VARIANT_3 = 0x218,
    ANIM_ACTION_STAND_TO_COWER = 0x219,
    ANIM_ACTION_STAND_TO_COWER_VARIANT_1 = 0x21A,
    ANIM_ACTION_STAND_TO_COWER_VARIANT_2 = 0x21B,
    ANIM_ACTION_STAND_TO_COWER_VARIANT_3 = 0x21C,
    ANIM_ACTION_STAND_TO_COWER_VARIANT_4 = 0x21D,
    ANIM_ACTION_STAND_TO_SURRENDER = 0x21E,
    ANIM_ACTION_SURRENDER_TO_STAND = 0x21F,
    ANIM_ACTION_SURRENDER_STALL_VARIANT_1 = 0x220,
    ANIM_ACTION_SURRENDER_STALL_VARIANT_2 = 0x221,
    ANIM_ACTION_SURRENDER_OPEN_SAFE = 0x222,
    ANIM_ACTION_TRANS_CROUCH_TO_STAND = 0x223,
    ANIM_ACTION_TRANS_STAND_TO_CROUCH = 0x224,
    ANIM_ACTION_MELEE_ATTACK_A = 0x225,
    ANIM_ACTION_MELEE_ATTACK_B = 0x226,
    ANIM_ACTION_MELEE_ATTACK_C = 0x227,
    ANIM_ACTION_MELEE_ATTACK_D = 0x228,
    ANIM_ACTION_MELEE_MOVE_ATTACK_A = 0x229,
    ANIM_ACTION_MELEE_MOVE_ATTACK_B = 0x22A,
    ANIM_ACTION_MELEE_PRONE_KICK = 0x22B,
    ANIM_ACTION_MELEE_PRONE_ATTACK = 0x22C,
    ANIM_ACTION_MELEE_KICK = 0x22D,
    ANIM_ACTION_MELEE_STEP_BACK = 0x22E,
    ANIM_ACTION_MELEE_STEP_FWD = 0x22F,
    ANIM_ACTION_STAND_FIRE = 0x230,
    ANIM_ACTION_STAND_FIRE_LHAND = 0x231,
    ANIM_ACTION_WALK_FIRE = 0x232,
    ANIM_ACTION_WALK_FIRE_LHAND = 0x233,
    ANIM_ACTION_WALK_FIRE_BACK = 0x234,
    ANIM_ACTION_WALK_FIRE_BACK_LHAND = 0x235,
    ANIM_ACTION_WALK_FIRE_LEFT = 0x236,
    ANIM_ACTION_WALK_FIRE_LEFT_LHAND = 0x237,
    ANIM_ACTION_WALK_FIRE_RIGHT = 0x238,
    ANIM_ACTION_WALK_FIRE_RIGHT_LHAND = 0x239,
    ANIM_ACTION_RUN_FIRE = 0x23A,
    ANIM_ACTION_RUN_FIRE_LHAND = 0x23B,
    ANIM_ACTION_RUN_FIRE_BACK = 0x23C,
    ANIM_ACTION_RUN_FIRE_BACK_LHAND = 0x23D,
    ANIM_ACTION_RUN_FIRE_LEFT = 0x23E,
    ANIM_ACTION_RUN_FIRE_LEFT_LHAND = 0x23F,
    ANIM_ACTION_RUN_FIRE_RIGHT = 0x240,
    ANIM_ACTION_RUN_FIRE_RIGHT_LHAND = 0x241,
    ANIM_ACTION_BACKPEDAL_FIRE_LEFT = 0x242,
    ANIM_ACTION_BACKPEDAL_FIRE_RIGHT = 0x243,
    ANIM_ACTION_CROUCH_FIRE = 0x244,
    ANIM_ACTION_CROUCH_FIRE_LHAND = 0x245,
    ANIM_ACTION_CROUCH_WALK_FIRE = 0x246,
    ANIM_ACTION_CROUCH_WALK_FIRE_LHAND = 0x247,
    ANIM_ACTION_CROUCH_WALK_FIRE_BACK = 0x248,
    ANIM_ACTION_CROUCH_WALK_FIRE_BACK_LHAND = 0x249,
    ANIM_ACTION_CROUCH_WALK_FIRE_LEFT = 0x24A,
    ANIM_ACTION_CROUCH_WALK_FIRE_LEFT_LHAND = 0x24B,
    ANIM_ACTION_CROUCH_WALK_FIRE_RIGHT = 0x24C,
    ANIM_ACTION_CROUCH_WALK_FIRE_RIGHT_LHAND = 0x24D,
    ANIM_ACTION_TRANS_READY_BACK_LEFT_TO_BACK_RIGHT = 0x24E,
    ANIM_ACTION_GRENADE_FIRE = 0x24F,
    ANIM_ACTION_GRENADE_WALK_FIRE = 0x250,
    ANIM_ACTION_GRENADE_WALK_FIRE_BACK = 0x251,
    ANIM_ACTION_GRENADE_WALK_FIRE_LEFT = 0x252,
    ANIM_ACTION_GRENADE_WALK_FIRE_RIGHT = 0x253,
    ANIM_ACTION_GRENADE_RUN_FIRE = 0x254,
    ANIM_ACTION_GRENADE_RUN_FIRE_BACK = 0x255,
    ANIM_ACTION_GRENADE_RUN_FIRE_LEFT = 0x256,
    ANIM_ACTION_GRENADE_RUN_FIRE_RIGHT = 0x257,
    ANIM_ACTION_GRENADE_CROUCH_FIRE = 0x258,
    ANIM_ACTION_GRENADE_CROUCH_WALK_FIRE = 0x259,
    ANIM_ACTION_GRENADE_CROUCH_WALK_FIRE_BACK = 0x25A,
    ANIM_ACTION_GRENADE_CROUCH_WALK_FIRE_LEFT = 0x25B,
    ANIM_ACTION_GRENADE_CROUCH_WALK_FIRE_RIGHT = 0x25C,
    ANIM_ACTION_GRENADE_RELOAD = 0x25D,
    ANIM_ACTION_GRENADE_RELOAD_MOVE = 0x25E,
    ANIM_ACTION_GRENADE_CROUCH_RELOAD = 0x25F,
    ANIM_ACTION_GRENADE_CROUCH_RELOAD_MOVE = 0x260,
    ANIM_ACTION_OFFHAND_READY_FORWARD = 0x261,
    ANIM_ACTION_OFFHAND_READY_RIGHT = 0x262,
    ANIM_ACTION_OFFHAND_READY_BACKPEDAL_LEFT = 0x263,
    ANIM_ACTION_OFFHAND_READY_BACK = 0x264,
    ANIM_ACTION_OFFHAND_READY_FORWARD_LEFT = 0x265,
    ANIM_ACTION_OFFHAND_READY_BACKPEDAL_RIGHT = 0x266,
    ANIM_ACTION_OFFHAND_READY_LEFT = 0x267,
    ANIM_ACTION_OFFHAND_READY_BACK_LEFT = 0x268,
    ANIM_ACTION_OFFHAND_READY_STAND = 0x269,
    ANIM_ACTION_OFFHAND_WALK_FORWARD = 0x26A,
    ANIM_ACTION_OFFHAND_WALK_LEFT = 0x26B,
    ANIM_ACTION_OFFHAND_WALK_RIGHT = 0x26C,
    ANIM_ACTION_OFFHAND_WALK_BACK = 0x26D,
    ANIM_ACTION_STAND_SHLDR_FIRE = 0x26E,
    ANIM_ACTION_WALK_SHLDR_FIRE = 0x26F,
    ANIM_ACTION_FIRE_SWEEP = 0x270,
    ANIM_ACTION_RELOAD = 0x271,
    ANIM_ACTION_RELOAD_VARIANT_1 = 0x272,
    ANIM_ACTION_RELOAD_VARIANT_2 = 0x273,
    ANIM_ACTION_RELOAD_VARIANT_3 = 0x274,
    ANIM_ACTION_WALK_RELOAD = 0x275,
    ANIM_ACTION_WALK_RELOAD_LEFT = 0x276,
    ANIM_ACTION_WALK_RELOAD_RIGHT = 0x277,
    ANIM_ACTION_WALK_RELOAD_BACK = 0x278,
    ANIM_ACTION_RUN_RELOAD = 0x279,
    ANIM_ACTION_RUN_RELOAD_LEFT = 0x27A,
    ANIM_ACTION_RUN_RELOAD_RIGHT = 0x27B,
    ANIM_ACTION_RUN_RELOAD_BACK = 0x27C,
    ANIM_ACTION_RUN_RELOAD_BACK_LEFT = 0x27D,
    ANIM_ACTION_BACKPEDAL_RELOAD_LEFT = 0x27E,
    ANIM_ACTION_CROUCH_RELOAD = 0x27F,
    ANIM_ACTION_CROUCH_WALK_RELOAD = 0x280,
    ANIM_ACTION_CROUCH_WALK_RELOAD_LEFT = 0x281,
    ANIM_ACTION_CROUCH_WALK_RELOAD_RIGHT = 0x282,
    ANIM_ACTION_CROUCH_COVER_RELOAD = 0x283,
    ANIM_ACTION_WEAPON_RELOAD_PLAYER = 0x284,
    ANIM_ACTION_FLASHBANG_TO_STAND = 0x285,
    ANIM_ACTION_PUNCH1_R = 0x286,
    ANIM_ACTION_PUNCH1_L = 0x287,
    ANIM_ACTION_PUNCH2_R = 0x288,
    ANIM_ACTION_PUNCH2_L = 0x289,
    ANIM_ACTION_FINISH2_L_VICTIM = 0x28A,
    ANIM_ACTION_BULLET_FLINCH_RIGHT = 0x28B,
    ANIM_ACTION_BULLET_FLINCH_LEFT = 0x28C,
    ANIM_ACTION_BULLET_FLINCH_BACK = 0x28D,
    ANIM_ACTION_BULLET_FLINCH_FRONT = 0x28E,
    ANIM_ACTION_MELEE_FLINCH_RIGHT_HIGH = 0x28F,
    ANIM_ACTION_MELEE_FLINCH_RIGHT_LOW = 0x290,
    ANIM_ACTION_MELEE_FLINCH_LEFT_HIGH = 0x291,
    ANIM_ACTION_MELEE_FLINCH_LEFT_LOW = 0x292,
    ANIM_ACTION_MELEE_FLINCH_BACK_HIGH = 0x293,
    ANIM_ACTION_MELEE_FLINCH_BACK_LOW = 0x294,
    ANIM_ACTION_MELEE_FLINCH_FRONT_HIGH = 0x295,
    ANIM_ACTION_MELEE_FLINCH_FRONT_LOW = 0x296,
    ANIM_ACTION_MELEE_FLINCH_FRONT_RIGHT_HIGH = 0x297,
    ANIM_ACTION_MELEE_FLINCH_FRONT_RIGHT_LOW = 0x298,
    ANIM_ACTION_MELEE_FLINCH_FRONT_LEFT_HIGH = 0x299,
    ANIM_ACTION_MELEE_FLINCH_FRONT_LEFT_LOW = 0x29A,
    ANIM_ACTION_FLINCH_FRONT = 0x29B,
    ANIM_ACTION_FLINCH_BACK = 0x29C,
    ANIM_ACTION_FLINCH_LEFT = 0x29D,
    ANIM_ACTION_FLINCH_RIGHT = 0x29E,
    ANIM_ACTION_BUMPED_FRONT_LEFT = 0x29F,
    ANIM_ACTION_BUMPED_FRONT_RIGHT = 0x2A0,
    ANIM_ACTION_BUMPED_BACK_LEFT = 0x2A1,
    ANIM_ACTION_BUMPED_BACK_RIGHT = 0x2A2,
    ANIM_ACTION_BUMPED_LEFT = 0x2A3,
    ANIM_ACTION_BUMPED_RIGHT = 0x2A4,
    ANIM_ACTION_BRUTE_WOUNDED = 0x2A5,
    ANIM_ACTION_BRUTE_DOWNED_FLINCH = 0x2A6,
    ANIM_ACTION_BRUTE_EXPLOSION_FLINCH = 0x2A7,
    ANIM_ACTION_AVOID_FACING_LEFT = 0x2A8,
    ANIM_ACTION_AVOID_FACING_RIGHT = 0x2A9,
    ANIM_ACTION_PUNCH_MOVE_L = 0x2AA,
    ANIM_ACTION_PUNCH_MOVE_R = 0x2AB,
    ANIM_ACTION_PRONE_STOMP_SHORT = 0x2AC,
    ANIM_ACTION_PRONE_STOMP_MED = 0x2AD,
    ANIM_ACTION_PRONE_STOMP_LONG = 0x2AE,
    ANIM_ACTION_PRONE_KICK_SHORT = 0x2AF,
    ANIM_ACTION_PRONE_KICK_MED = 0x2B0,
    ANIM_ACTION_PRONE_KICK_LONG = 0x2B1,
    ANIM_ACTION_BK_FALLDOWN = 0x2B2,
    ANIM_ACTION_BK_GETUP = 0x2B3,
    ANIM_ACTION_FW_GETUP = 0x2B4,
    ANIM_ACTION_BK_GETUP_TO_DBNO = 0x2B5,
    ANIM_ACTION_FW_GETUP_TO_DBNO = 0x2B6,
    ANIM_ACTION_DEATH = 0x2B7,
    ANIM_ACTION_DBNO_DEATH_UNARMED = 0x2B8,
    ANIM_ACTION_FACE_FIRE = 0x2B9,
    ANIM_ACTION_CROUCH_FLINCH_LEFT = 0x2BA,
    ANIM_ACTION_CROUCH_FLINCH_RIGHT = 0x2BB,
    ANIM_ACTION_CROUCH_FLINCH_FRONT = 0x2BC,
    ANIM_ACTION_CROUCH_FLINCH_BACK = 0x2BD,
    ANIM_ACTION_STUNGUN_FLINCH = 0x2BE,
    ANIM_ACTION_TOSS_ITEM = 0x2BF,
    ANIM_ACTION_TOSS_ITEM_MOVE = 0x2C0,
    ANIM_ACTION_TOSS_ITEM_BACK_MOVE = 0x2C1,
    ANIM_ACTION_TOSS_ITEM_LEFT_MOVE = 0x2C2,
    ANIM_ACTION_BRUTE_THROW_ITEM = 0x2C3,
    ANIM_ACTION_THROW_ITEM_MOVE = 0x2C4,
    ANIM_ACTION_THROW_ITEM_BACK = 0x2C5,
    ANIM_ACTION_THROW_ITEM_BACK_MOVE = 0x2C6,
    ANIM_ACTION_THROW_ITEM_MOVE_LEFT = 0x2C7,
    ANIM_ACTION_THROW_BASKETBALL = 0x2C8,
    ANIM_ACTION_HORRIFIED = 0x2C9,
    ANIM_ACTION_HORRIFIED_B = 0x2CA,
    ANIM_ACTION_HORRIFIED_C = 0x2CB,
    ANIM_ACTION_STARTLED = 0x2CC,
    ANIM_ACTION_REACT_APPLAUSE = 0x2CD,
    ANIM_ACTION_DRUNK_VOMIT = 0x2CE,
    ANIM_ACTION_REACT_WAVE = 0x2CF,
    ANIM_ACTION_REACT_STREAK_POSITIVE_A = 0x2D0,
    ANIM_ACTION_REACT_STREAK_POSITIVE_B = 0x2D1,
    ANIM_ACTION_REACT_STREAK_POSITIVE_C = 0x2D2,
    ANIM_ACTION_REACT_STREAK_NEGATIVE_A = 0x2D3,
    ANIM_ACTION_AFF_ITEM_HIGH = 0x2D4,
    ANIM_ACTION_AFF_ITEM_MID = 0x2D5,
    ANIM_ACTION_TALK_CONFRONTATIONAL = 0x2D6,
    ANIM_ACTION_TALK_DISRESPECT = 0x2D7,
    ANIM_ACTION_START_TURN_LEFT = 0x2D8,
    ANIM_ACTION_START_TURN_RIGHT = 0x2D9,
    ANIM_ACTION_STAND_TURN_LEFT_90 = 0x2DA,
    ANIM_ACTION_STAND_TURN_RIGHT_90 = 0x2DB,
    ANIM_ACTION_STAND_TURN_LEFT_90_B = 0x2DC,
    ANIM_ACTION_STAND_TURN_RIGHT_90_B = 0x2DD,
    ANIM_ACTION_STAND_TURN_LEFT_180 = 0x2DE,
    ANIM_ACTION_STAND_TURN_RIGHT_180 = 0x2DF,
    ANIM_ACTION_CROUCH_TURN_LEFT_90 = 0x2E0,
    ANIM_ACTION_CROUCH_TURN_RIGHT_90 = 0x2E1,
    ANIM_ACTION_CROUCH_TURN_LEFT_180 = 0x2E2,
    ANIM_ACTION_CROUCH_TURN_RIGHT_180 = 0x2E3,
    ANIM_ACTION_END_TURN_LEFT = 0x2E4,
    ANIM_ACTION_END_TURN_RIGHT = 0x2E5,
    ANIM_ACTION_PISTOL_END_TURN_LEFT = 0x2E6,
    ANIM_ACTION_PISTOL_END_TURN_RIGHT = 0x2E7,
    ANIM_ACTION_DBNO_TURN_LEFT = 0x2E8,
    ANIM_ACTION_DBNO_TURN_RIGHT = 0x2E9,
    ANIM_ACTION_USE_LIQUOR = 0x2EA,
    ANIM_ACTION_USE_LIQUOR_MOVE = 0x2EB,
    ANIM_ACTION_USE_BLUNT = 0x2EC,
    ANIM_ACTION_USE_BLUNT_MOVE = 0x2ED,
    ANIM_ACTION_USE_FOOD = 0x2EE,
    ANIM_ACTION_USE_FOOD_MOVE = 0x2EF,
    ANIM_ACTION_USE_FOOD_CROUCH = 0x2F0,
    ANIM_ACTION_USE_DRINK = 0x2F1,
    ANIM_ACTION_USE_DRINK_MOVE = 0x2F2,
    ANIM_ACTION_USE_DRINK_CROUCH = 0x2F3,
    ANIM_ACTION_SELL_SHADY = 0x2F4,
    ANIM_ACTION_BUY_SHADY = 0x2F5,
    ANIM_ACTION_SELL_ITEM = 0x2F6,
    ANIM_ACTION_BUY_ITEM = 0x2F7,
    ANIM_ACTION_POUR_OUT = 0x2F8,
    ANIM_ACTION_STAND_TURN = 0x2F9,
    ANIM_ACTION_RUN_STOP = 0x2FA,
    ANIM_ACTION_RUNNING_TURN = 0x2FB,
    ANIM_ACTION_RUNNING_TURN_PIMP = 0x2FC,
    ANIM_ACTION_JOG_180 = 0x2FD,
    ANIM_ACTION_SPRINT_180 = 0x2FE,
    ANIM_ACTION_RUN_TURN_180_LEFT = 0x2FF,
    ANIM_ACTION_RUN_TURN_180_RIGHT = 0x300,
    ANIM_ACTION_SPRINT_TURN_180_LEFT = 0x301,
    ANIM_ACTION_SPRINT_TURN_180_RIGHT = 0x302,
    ANIM_ACTION_SPRINT_TURN_180_LEFT_WEAPON = 0x303,
    ANIM_ACTION_SPRINT_TURN_180_RIGHT_WEAPON = 0x304,
    ANIM_ACTION_TRANS_SPRINT_TO_RUN = 0x305,
    ANIM_ACTION_TRANS_RUN_TO_SPRINT = 0x306,
    ANIM_ACTION_KICK_DOOR = 0x307,
    ANIM_ACTION_PUSH_DOOR = 0x308,
    ANIM_ACTION_DUST_OFF = 0x309,
    ANIM_ACTION_VOMIT_STAND = 0x30A,
    ANIM_ACTION_COUGH_STAND = 0x30B,
    ANIM_ACTION_TRANS_STAND_TO_READY = 0x30C,
    ANIM_ACTION_TRANS_READY_TO_STAND = 0x30D,
    ANIM_ACTION_TRANS_READY_TO_CROUCH = 0x30E,
    ANIM_ACTION_TRANS_CROUCH_TO_READY = 0x30F,
    ANIM_ACTION_TRANS_CROUCH_READY_TO_CROUCH = 0x310,
    ANIM_ACTION_TRANS_CROUCH_TO_CROUCH_READY = 0x311,
    ANIM_ACTION_TRANS_READY_TO_CROUCH_READY = 0x312,
    ANIM_ACTION_TRANS_CROUCH_READY_TO_READY = 0x313,
    ANIM_ACTION_TRANS_STAND_TO_CAR_LEAN = 0x314,
    ANIM_ACTION_TRANS_MELEE_COMBAT_TO_STAND = 0x315,
    ANIM_ACTION_TRANS_STAND_TO_MELEE_COMBAT = 0x316,
    ANIM_ACTION_TRANS_STAND_TO_PANT = 0x317,
    ANIM_ACTION_TRANS_PANT_TO_STAND = 0x318,
    ANIM_ACTION_TRANS_WALK_TO_STOP = 0x319,
    ANIM_ACTION_TRANS_RUN_TO_STOP = 0x31A,
    ANIM_ACTION_TRANS_RUN_TO_STOP_RIGHT = 0x31B,
    ANIM_ACTION_TRANS_STAND_TO_RUN_FORWARD = 0x31C,
    ANIM_ACTION_TRANS_STAND_TO_RUN_LEFT = 0x31D,
    ANIM_ACTION_TRANS_STAND_TO_RUN_RIGHT = 0x31E,
    ANIM_ACTION_TRANS_STAND_TO_RUN_BACK = 0x31F,
    ANIM_ACTION_TRANS_STAND_TO_WALK_FORWARD = 0x320,
    ANIM_ACTION_TRANS_STAND_TO_WALK_LEFT = 0x321,
    ANIM_ACTION_TRANS_STAND_TO_WALK_RIGHT = 0x322,
    ANIM_ACTION_TRANS_STAND_TO_WALK_BACK = 0x323,
    ANIM_ACTION_FALSE_START = 0x324,
    ANIM_ACTION_TRANS_SPRINT_TO_STOP = 0x325,
    ANIM_ACTION_TRANS_SPRINT_TO_STOP_WEAPON = 0x326,
    ANIM_ACTION_TRANS_VI_RUN_TO_STOP = 0x327,
    ANIM_ACTION_TRANS_RUN_TO_READY_FORWARD = 0x328,
    ANIM_ACTION_TRANS_RUN_TO_READY_LEFT = 0x329,
    ANIM_ACTION_TRANS_RUN_TO_READY_RIGHT = 0x32A,
    ANIM_ACTION_TRANS_RUN_TO_READY_BACK = 0x32B,
    ANIM_ACTION_TRANS_HS_RUN_BACK_TO_STOP_A = 0x32C,
    ANIM_ACTION_TRANS_HS_RUN_BACK_TO_STOP_B = 0x32D,
    ANIM_ACTION_TRANS_HS_RUN_LEFT_TO_STOP_A = 0x32E,
    ANIM_ACTION_TRANS_HS_RUN_LEFT_TO_STOP_B = 0x32F,
    ANIM_ACTION_TRANS_HS_RUN_RIGHT_TO_STOP_A = 0x330,
    ANIM_ACTION_TRANS_HS_RUN_RIGHT_TO_STOP_B = 0x331,
    ANIM_ACTION_TRANS_HS_RUN_TO_STOP_A = 0x332,
    ANIM_ACTION_TRANS_HS_RUN_TO_STOP_B = 0x333,
    ANIM_ACTION_TRANS_WALK_TO_STAND = 0x334,
    ANIM_ACTION_TRANS_WALK_TO_STAND_B = 0x335,
    ANIM_ACTION_TRANS_SKID_TO_STOP = 0x336,
    ANIM_ACTION_TRANS_DBNO_CRAWL_TO_DOWN = 0x337,
    ANIM_ACTION_TRANS_DBNO_DOWN_TO_CRAWL = 0x338,
    ANIM_ACTION_TRANS_STAND_TO_DBNO = 0x339,
    ANIM_ACTION_TRANS_STAND_TO_DBNO_UNARMED = 0x33A,
    ANIM_ACTION_TRANS_DBNO_TO_STAND_UNARMED = 0x33B,
    ANIM_ACTION_TRANS_RAGDOLL_FORWARD_TO_SWIM = 0x33C,
    ANIM_ACTION_UNIQUE_PIMP_SLAP = 0x33D,
    ANIM_ACTION_HO_SLAP_FLINCH = 0x33E,
    ANIM_ACTION_CELL_DIAL = 0x33F,
    ANIM_ACTION_CELL_TAKE_PIX = 0x340,
    ANIM_ACTION_TOURIST_TAKE_PIX = 0x341,
    ANIM_ACTION_STAND_WRITE = 0x342,
    ANIM_ACTION_MP_TAUNT_ONE = 0x343,
    ANIM_ACTION_MP_TAUNT_TWO = 0x344,
    ANIM_ACTION_MP_TAUNT_THREE = 0x345,
    ANIM_ACTION_STAND_TO_CARRY = 0x346,
    ANIM_ACTION_PYROBOX_THROW = 0x347,
    ANIM_ACTION_PYROBOX_TOSS = 0x348,
    ANIM_ACTION_THEFT_OPEN_SAFE = 0x349,
    ANIM_ACTION_ARREST_FACE_DOWN_LEFT = 0x34A,
    ANIM_ACTION_ARRESTED_FACE_DOWN_LEFT = 0x34B,
    ANIM_ACTION_ARREST_FACE_DOWN_RIGHT = 0x34C,
    ANIM_ACTION_ARRESTED_FACE_DOWN_RIGHT = 0x34D,
    ANIM_ACTION_ARREST_FACE_UP_LEFT = 0x34E,
    ANIM_ACTION_ARRESTED_FACE_UP_LEFT = 0x34F,
    ANIM_ACTION_ARREST_FACE_UP_RIGHT = 0x350,
    ANIM_ACTION_ARRESTED_FACE_UP_RIGHT = 0x351,
    ANIM_ACTION_ARREST_STANDING = 0x352,
    ANIM_ACTION_ARRESTING_STANDING = 0x353,
    ANIM_ACTION_TEARGASSED = 0x354,
    ANIM_ACTION_TRANS_ZOMBIE_EAT_TO_STAND = 0x355,
    ANIM_ACTION_TRANS_STAND_TO_ZOMBIE_EAT = 0x356,
    ANIM_ACTION_ZOMBIE_EXPLODE = 0x357,
    ANIM_ACTION_ZOMBIE_GRAB_A = 0x358,
    ANIM_ACTION_ZOMBIE_GRAB_A_VICTIM = 0x359,
    ANIM_ACTION_ZOMBIE_GRAB_A_RELEASE = 0x35A,
    ANIM_ACTION_ZOMBIE_GRAB_A_RELEASE_VICTIM = 0x35B,
    ANIM_ACTION_ZOMBIE_GRAB_B = 0x35C,
    ANIM_ACTION_ZOMBIE_GRAB_B_VICTIM = 0x35D,
    ANIM_ACTION_ZOMBIE_GRAB_B_RELEASE = 0x35E,
    ANIM_ACTION_ZOMBIE_GRAB_B_RELEASE_VICTIM = 0x35F,
    ANIM_ACTION_PLANT_BOMB = 0x360,
    ANIM_ACTION_HS_POUR_OUT = 0x361,
    ANIM_ACTION_HS_VICTIM_POUR_OUT = 0x362,
    ANIM_ACTION_HS_IDLE_A = 0x363,
    ANIM_ACTION_HS_IDLE_B = 0x364,
    ANIM_ACTION_HS_RELOAD = 0x365,
    ANIM_ACTION_HS_FIRE = 0x366,
    ANIM_ACTION_HS_FIRE_LEFT = 0x367,
    ANIM_ACTION_HS_FIRE_RIGHT = 0x368,
    ANIM_ACTION_HSG_THROW = 0x369,
    ANIM_ACTION_HSG_VICTIM_THROW = 0x36A,
    ANIM_ACTION_HGS_TOSS = 0x36B,
    ANIM_ACTION_HGS_VICTIM_TOSS = 0x36C,
    ANIM_ACTION_HGS_THROW_MOVE = 0x36D,
    ANIM_ACTION_CUST_STAND_TO_BACKPACK_M = 0x36E,
    ANIM_ACTION_CUST_BACKPACK_TO_STAND_M = 0x36F,
    ANIM_ACTION_CUST_STAND_TO_FEET_M = 0x370,
    ANIM_ACTION_CUST_FEET_TO_STAND_M = 0x371,
    ANIM_ACTION_CUST_STAND_TO_LOWER_M = 0x372,
    ANIM_ACTION_CUST_LOWER_TO_STAND_M = 0x373,
    ANIM_ACTION_CUST_STAND_TO_UPPER_M = 0x374,
    ANIM_ACTION_CUST_UPPER_TO_STAND_M = 0x375,
    ANIM_ACTION_CUST_STAND_TO_WRIST_M = 0x376,
    ANIM_ACTION_CUST_WRIST_TO_STAND_M = 0x377,
    ANIM_ACTION_CUST_STAND_TO_BACKPACK_F = 0x378,
    ANIM_ACTION_CUST_BACKPACK_TO_STAND_F = 0x379,
    ANIM_ACTION_CUST_STAND_TO_FEET_F = 0x37A,
    ANIM_ACTION_CUST_FEET_TO_STAND_F = 0x37B,
    ANIM_ACTION_CUST_STAND_TO_LOWER_F = 0x37C,
    ANIM_ACTION_CUST_LOWER_TO_STAND_F = 0x37D,
    ANIM_ACTION_CUST_STAND_TO_UPPER_F = 0x37E,
    ANIM_ACTION_CUST_UPPER_TO_STAND_F = 0x37F,
    ANIM_ACTION_CUST_STAND_TO_WRIST_F = 0x380,
    ANIM_ACTION_CUST_WRIST_TO_STAND_F = 0x381,
    ANIM_ACTION_INSULT_A = 0x382,
    ANIM_ACTION_INSULT_B = 0x383,
    ANIM_ACTION_INSULT_C = 0x384,
    ANIM_ACTION_INSULT_D = 0x385,
    ANIM_ACTION_INSULT_E = 0x386,
    ANIM_ACTION_INSULT_F = 0x387,
    ANIM_ACTION_INSULT_G = 0x388,
    ANIM_ACTION_INSULT_H = 0x389,
    ANIM_ACTION_INSULT_I = 0x38A,
    ANIM_ACTION_INSULT_J = 0x38B,
    ANIM_ACTION_INSULT_K = 0x38C,
    ANIM_ACTION_INSULT_L = 0x38D,
    ANIM_ACTION_INSULT_M = 0x38E,
    ANIM_ACTION_INSULT_N = 0x38F,
    ANIM_ACTION_INSULT_O = 0x390,
    ANIM_ACTION_INSULT_P = 0x391,
    ANIM_ACTION_INSULT_Q = 0x392,
    ANIM_ACTION_INSULT_R = 0x393,
    ANIM_ACTION_INSULT_S = 0x394,
    ANIM_ACTION_INSULT_T = 0x395,
    ANIM_ACTION_INSULT_U = 0x396,
    ANIM_ACTION_INSULT_V = 0x397,
    ANIM_ACTION_INSULT_W = 0x398,
    ANIM_ACTION_INSULT_X = 0x399,
    ANIM_ACTION_INSULT_Y = 0x39A,
    ANIM_ACTION_INSULT_Z = 0x39B,
    ANIM_ACTION_INSULT_AA = 0x39C,
    ANIM_ACTION_COMPLIMENT_A = 0x39D,
    ANIM_ACTION_COMPLIMENT_B = 0x39E,
    ANIM_ACTION_COMPLIMENT_C = 0x39F,
    ANIM_ACTION_COMPLIMENT_D = 0x3A0,
    ANIM_ACTION_COMPLIMENT_E = 0x3A1,
    ANIM_ACTION_COMPLIMENT_F = 0x3A2,
    ANIM_ACTION_COMPLIMENT_G = 0x3A3,
    ANIM_ACTION_COMPLIMENT_H = 0x3A4,
    ANIM_ACTION_COMPLIMENT_I = 0x3A5,
    ANIM_ACTION_COMPLIMENT_J = 0x3A6,
    ANIM_ACTION_COMPLIMENT_K = 0x3A7,
    ANIM_ACTION_COMPLIMENT_L = 0x3A8,
    ANIM_ACTION_COMPLIMENT_M = 0x3A9,
    ANIM_ACTION_COMPLIMENT_N = 0x3AA,
    ANIM_ACTION_COMPLIMENT_O = 0x3AB,
    ANIM_ACTION_COMPLIMENT_P = 0x3AC,
    ANIM_ACTION_COMPLIMENT_Q = 0x3AD,
    ANIM_ACTION_COMPLIMENT_R = 0x3AE,
    ANIM_ACTION_COMPLIMENT_S = 0x3AF,
    ANIM_ACTION_COMPLIMENT_T = 0x3B0,
    ANIM_ACTION_COMPLIMENT_U = 0x3B1,
    ANIM_ACTION_COMPLIMENT_V = 0x3B2,
    ANIM_ACTION_COMPLIMENT_W = 0x3B3,
    ANIM_ACTION_COMPLIMENT_X = 0x3B4,
    ANIM_ACTION_COMPLIMENT_Y = 0x3B5,
    ANIM_ACTION_COMPLIMENT_Z = 0x3B6,
    ANIM_ACTION_COMPLIMENT_AA = 0x3B7,
    ANIM_ACTION_COMPLIMENT_BB = 0x3B8,
    ANIM_ACTION_COMPLIMENT_CC = 0x3B9,
    ANIM_ACTION_COMPLIMENT_DD = 0x3BA,
    ANIM_ACTION_BRUTE_CAR_RAM = 0x3BB,
    ANIM_ACTION_BRUTE_CAR_STOMP = 0x3BC,
    ANIM_ACTION_BRUTE_CAR_FLIP = 0x3BD,
    ANIM_ACTION_FLASHING_OPEN_COAT = 0x3BE,
    ANIM_ACTION_FLASHING_CLOSE_COAT = 0x3BF,
    ANIM_ACTION_HOSE_CONNECT = 0x3C0,
    ANIM_ACTION_HOSE_DISCONNECT = 0x3C1,
    ANIM_ACTION_HOSE_FIRE = 0x3C2,
    ANIM_ACTION_USE_VOODOO = 0x3C3,
    ANIM_ACTION_M01_Z01_TRANSITION = 0x3C4,
    ANIM_ACTION_MELEE_GRAB_B = 0x3C5,
    ANIM_ACTION_MELEE_GRAB_REVERSAL_A = 0x3C6,
    ANIM_ACTION_UNCUFF_GIVE = 0x3C7,
    ANIM_ACTION_UNCUFF_RECEIVE = 0x3C8,
    ANIM_ACTION_VEHICLE_SURF_HANDSTAND_TO_STAND = 0x3C9,
    ANIM_ACTION_VEHICLE_SURF_STAND_TO_HANDSTAND = 0x3CA,
    ANIM_ACTION_CPR_STAND_TO_CROUCH = 0x3CB,
    ANIM_ACTION_CPR_CROUCH_TO_STAND = 0x3CC,
    ANIM_ACTION_CPR_CROUCH_PRESS = 0x3CD,
    ANIM_ACTION_CPR_LIEDOWN_FLINCH = 0x3CE,
    ANIM_ACTION_FINISHER_KILL_A = 0x3CF,
    ANIM_ACTION_FINISHER_KILL_B = 0x3D0,
    ANIM_ACTION_FINISHER_ESCAPE_A = 0x3D1,
    ANIM_ACTION_FINISHER_ESCAPE_B = 0x3D2,
    ANIM_ACTION_FINISHER_KILL_2A = 0x3D3,
    ANIM_ACTION_FINISHER_KILL_2B = 0x3D4,
    ANIM_ACTION_GRAPPLE_ESCAPE_ATTACKER = 0x3D5,
    ANIM_ACTION_GRAPPLE_ESCAPE_VICTIM = 0x3D6,
    ANIM_ACTION_PICKUP_ITEM = 0x3D7,
    ANIM_ACTION_PICKUP_ITEM_UPRIGHT = 0x3D8,
    ANIM_ACTION_DETONATE = 0x3D9,
    ANIM_ACTION_TRANS_RIDE_SIT_TO_AIM = 0x3DA,
    ANIM_ACTION_DRIVE_FIRE = 0x3DB,
    ANIM_ACTION_DRIVE_FIRE_LEFT = 0x3DC,
    ANIM_ACTION_DRIVE_FIRE_RIGHT = 0x3DD,
    ANIM_ACTION_DRIVE_FIRE_BACK = 0x3DE,
    ANIM_ACTION_RIDE_FIRE = 0x3DF,
    ANIM_ACTION_RIDE_RIGHT_FIRE_LEFT = 0x3E0,
    ANIM_ACTION_RIDE_FIRE_LEFT_NO_WINDOW = 0x3E1,
    ANIM_ACTION_RIDE_RIGHT_FIRE_RIGHT = 0x3E2,
    ANIM_ACTION_RIDE_RIGHT_FIRE_BACK = 0x3E3,
    ANIM_ACTION_RIDE_LEFT_FIRE = 0x3E4,
    ANIM_ACTION_RIDE_LEFT_FIRE_LEFT = 0x3E5,
    ANIM_ACTION_RIDE_LEFT_FIRE_RIGHT = 0x3E6,
    ANIM_ACTION_RIDE_LEFT_FIRE_RIGHT_NO_WINDOW = 0x3E7,
    ANIM_ACTION_RIDE_LEFT_FIRE_BACK = 0x3E8,
    ANIM_ACTION_RIDE_LEFTBACK_FIRE = 0x3E9,
    ANIM_ACTION_RIDE_LEFTBACK_FIRE_LEFT = 0x3EA,
    ANIM_ACTION_RIDE_LEFTBACK_FIRE_RIGHT = 0x3EB,
    ANIM_ACTION_RIDE_LEFTBACK_FIRE_BACK = 0x3EC,
    ANIM_ACTION_RIDE_RIGHTBACK_FIRE = 0x3ED,
    ANIM_ACTION_RIDE_RIGHTBACK_FIRE_LEFT = 0x3EE,
    ANIM_ACTION_RIDE_RIGHTBACK_FIRE_RIGHT = 0x3EF,
    ANIM_ACTION_RIDE_RIGHTBACK_FIRE_BACK = 0x3F0,
    ANIM_ACTION_DRIVER_ANGRY = 0x3F1,
    ANIM_ACTION_PASSENGER_ANGRY = 0x3F2,
    ANIM_ACTION_DRIVER_PASSENGER_ANGRY = 0x3F3,
    ANIM_ACTION_VEHICLE_RELOAD = 0x3F4,
    ANIM_ACTION_PASSENGER_RELOAD = 0x3F5,
    ANIM_ACTION_DPASSENGER_RELOAD = 0x3F6,
    ANIM_ACTION_PASSENGER_BACK_RELOAD = 0x3F7,
    ANIM_ACTION_DPASSENGER_BACK_RELOAD = 0x3F8,
    ANIM_ACTION_RIGHTBACK_RELOAD = 0x3F9,
    ANIM_ACTION_LEFTBACK_RELOAD = 0x3FA,
    ANIM_ACTION_THROW_ITEM_DRIVE = 0x3FB,
    ANIM_ACTION_THROW_ITEM_DRIVE_LEFT = 0x3FC,
    ANIM_ACTION_THROW_ITEM_DRIVE_RIGHT = 0x3FD,
    ANIM_ACTION_THROW_ITEM_DRIVE_RIGHT_TRUCKS = 0x3FE,
    ANIM_ACTION_THROW_ITEM_DRIVE_BACK = 0x3FF,
    ANIM_ACTION_THROW_ITEM_RIDE = 0x400,
    ANIM_ACTION_THROW_ITEM_RIDE_LEFT = 0x401,
    ANIM_ACTION_THROW_ITEM_RIDE_RIGHT = 0x402,
    ANIM_ACTION_THROW_ITEM_RIDE_BACK = 0x403,
    ANIM_ACTION_THROW_ITEM_RIDE_L = 0x404,
    ANIM_ACTION_THROW_ITEM_RIDE_L_LEFT = 0x405,
    ANIM_ACTION_THROW_ITEM_RIDE_L_RIGHT = 0x406,
    ANIM_ACTION_THROW_ITEM_RIDE_L_BACK = 0x407,
    ANIM_ACTION_VEHICLE_SITTING_CONVULSE = 0x408,
    ANIM_ACTION_OPEN_DOOR_OUTSIDE_DRIVER = 0x409,
    ANIM_ACTION_OPEN_DOOR_OUTSIDE_PASS = 0x40A,
    ANIM_ACTION_CLOSE_DOOR_INSIDE_DRIVER = 0x40B,
    ANIM_ACTION_CLOSE_DOOR_INSIDE_PASS_LEFT = 0x40C,
    ANIM_ACTION_CLOSE_DOOR_INSIDE_PASS_RIGHT = 0x40D,
    ANIM_ACTION_CLOSE_GULLWING_INSIDE_DRIVER = 0x40E,
    ANIM_ACTION_CLOSE_GULLWING_INSIDE_PASS = 0x40F,
    ANIM_ACTION_DIVE_DRIVER = 0x410,
    ANIM_ACTION_VEHICLE_FLINCH_LEFT_DRIVER = 0x411,
    ANIM_ACTION_VEHICLE_FLINCH_RIGHT_DRIVER = 0x412,
    ANIM_ACTION_VEHICLE_FLINCH_FRONT_DRIVER = 0x413,
    ANIM_ACTION_VEHICLE_FLINCH_BACK_DRIVER = 0x414,
    ANIM_ACTION_VEHICLE_FLINCH_LEFT_PASSENGER = 0x415,
    ANIM_ACTION_VEHICLE_FLINCH_RIGHT_PASSENGER = 0x416,
    ANIM_ACTION_VEHICLE_FLINCH_FRONT_PASSENGER = 0x417,
    ANIM_ACTION_VEHICLE_FLINCH_BACK_PASSENGER = 0x418,
    ANIM_ACTION_VEHICLE_FLINCH_LEFT_REAR_DRIVER = 0x419,
    ANIM_ACTION_VEHICLE_FLINCH_RIGHT_REAR_DRIVER = 0x41A,
    ANIM_ACTION_VEHICLE_FLINCH_FRONT_REAR_DRIVER = 0x41B,
    ANIM_ACTION_VEHICLE_FLINCH_BACK_REAR_DRIVER = 0x41C,
    ANIM_ACTION_HELI_FLINCH_DRIVER = 0x41D,
    ANIM_ACTION_HELI_FLINCH_DRIVER_REAR = 0x41E,
    ANIM_ACTION_HELI_FLINCH_PASSENGER_REAR = 0x41F,
    ANIM_ACTION_HELI_FLINCH_DRIVER_FLOOR = 0x420,
    ANIM_ACTION_HELI_FLINCH_PASSENGER_FLOOR = 0x421,
    ANIM_ACTION_HELI_PASSENGER_FIRE = 0x422,
    ANIM_ACTION_HELI_PASSENGER_RELOAD = 0x423,
    ANIM_ACTION_HELI_REAR_DRIVER_FIRE = 0x424,
    ANIM_ACTION_HELI_REAR_DRIVER_RELOAD = 0x425,
    ANIM_ACTION_HELI_PASSENGER_FIRE_A = 0x426,
    ANIM_ACTION_HELI_PASSENGER_FIRE_B = 0x427,
    ANIM_ACTION_HELI_PASSENGER_FIRE_C = 0x428,
    ANIM_ACTION_HELI_PASSENGER_RELOAD_A = 0x429,
    ANIM_ACTION_HELI_PASSENGER_RELOAD_B = 0x42A,
    ANIM_ACTION_HELI_VAULT_RIDER_RELOAD = 0x42B,
    ANIM_ACTION_HELI_VAULT_RIDER_RELOAD02 = 0x42C,
    ANIM_ACTION_HELI_VAULT_RIDER_RELOAD03 = 0x42D,
    ANIM_ACTION_HELI_VAULT_RIDER_RELOAD04 = 0x42E,
    ANIM_ACTION_HELI_VAULT_RIDER_RELOAD13 = 0x42F,
    ANIM_ACTION_BALL_RELOAD_01 = 0x430,
    ANIM_ACTION_BALL_RELOAD_02 = 0x431,
    ANIM_ACTION_BALL_RELOAD_03 = 0x432,
    ANIM_ACTION_BALL_RELOAD_04 = 0x433,
    ANIM_ACTION_BALL_RELOAD_05 = 0x434,
    ANIM_ACTION_BALL_RELOAD_06 = 0x435,
    ANIM_ACTION_RIDE_FIRE_BACK = 0x436,
    ANIM_ACTION_RIDE_FIRE_FORWARD = 0x437,
    ANIM_ACTION_RIDE_FIRE_LEFT = 0x438,
    ANIM_ACTION_RIDE_FIRE_RIGHT = 0x439,
    ANIM_ACTION_RIDE_RELOAD = 0x43A,
    ANIM_ACTION_REACT_NUT_SHOT = 0x43B,
    ANIM_ACTION_PARACHUTE_PULL_RIPCORD = 0x43C,
    ANIM_ACTION_PARACHUTE_LAND = 0x43D,
    ANIM_ACTION_RAPPEL_ENTER_HIGH = 0x43E,
    ANIM_ACTION_RAPPEL_ENTER_LOW = 0x43F,
    ANIM_ACTION_RAPPEL_LAND = 0x440,
    ANIM_ACTION_FALL_TO_FREEFALL = 0x441,
    ANIM_ACTION_FREEFALL_DEATH = 0x442,
    ANIM_ACTION_CHAINSAW_ATTACK_FRONT_A = 0x443,
    ANIM_ACTION_CHAINSAW_ATTACK_FRONT_B = 0x444,
    ANIM_ACTION_CHAINSAW_ATTACK_BACK_A = 0x445,
    ANIM_ACTION_CHAINSAW_ATTACK_BACK_B = 0x446,
    ANIM_ACTION_ANGEL_TRANS_STAND_TO_READY = 0x447,
    ANIM_ACTION_ANGEL_TRANS_READY_TO_STAND = 0x448,
    ANIM_ACTION_FINE_AIM_FIRE = 0x449,
    ANIM_ACTION_GANG_CUST_IDLE_MALE_A = 0x44A,
    ANIM_ACTION_GANG_CUST_IDLE_MALE_B = 0x44B,
    ANIM_ACTION_GANG_CUST_IDLE_FEMALE_A = 0x44C,
    ANIM_ACTION_GANG_CUST_IDLE_FEMALE_B = 0x44D,
    ANIM_ACTION_WATERMELON_LONG = 0x44E,
    ANIM_ACTION_COVER_CROUCH_ENTER_LEFT = 0x44F,
    ANIM_ACTION_COVER_CROUCH_ENTER_RIGHT = 0x450,
    ANIM_ACTION_COVER_CROUCH_ENTER_BACK = 0x451,
    ANIM_ACTION_COVER_CROUCH_ENTER_AROUND_LEFT = 0x452,
    ANIM_ACTION_COVER_CROUCH_ENTER_AROUND_RIGHT = 0x453,
    ANIM_ACTION_COVER_CROUCH_ENTER_OVER_BACK = 0x454,
    ANIM_ACTION_COVER_CROUCH_ENTER_OVER_FRONT = 0x455,
    ANIM_ACTION_COVER_CROUCH_ENTER_FAR_LEFT = 0x456,
    ANIM_ACTION_COVER_CROUCH_ENTER_FAR_RIGHT = 0x457,
    ANIM_ACTION_COVER_CROUCH_ENTER_FAR_BACK = 0x458,
    ANIM_ACTION_COVER_CROUCH_ENTER_LEFT_LOW = 0x459,
    ANIM_ACTION_COVER_CROUCH_ENTER_RIGHT_LOW = 0x45A,
    ANIM_ACTION_COVER_CROUCH_ENTER_FROM_RUN = 0x45B,
    ANIM_ACTION_COVER_STAND_ENTER_LEFT = 0x45C,
    ANIM_ACTION_COVER_STAND_ENTER_RIGHT = 0x45D,
    ANIM_ACTION_COVER_STAND_ENTER_BACK = 0x45E,
    ANIM_ACTION_COVER_STAND_ENTER_AROUND_LEFT = 0x45F,
    ANIM_ACTION_COVER_STAND_ENTER_AROUND_RIGHT = 0x460,
    ANIM_ACTION_COVER_STAND_ENTER_FAR_LEFT = 0x461,
    ANIM_ACTION_COVER_STAND_ENTER_FAR_RIGHT = 0x462,
    ANIM_ACTION_COVER_STAND_ENTER_FAR_BACK = 0x463,
    ANIM_ACTION_COVER_STAND_ENTER_LEFT_LOW = 0x464,
    ANIM_ACTION_COVER_STAND_ENTER_RIGHT_LOW = 0x465,
    ANIM_ACTION_COVER_STAND_ENTER_FROM_RUN = 0x466,
    ANIM_ACTION_COVER_CROUCH_OUT_BACK = 0x467,
    ANIM_ACTION_COVER_CROUCH_OUT_LEFT_HIGH = 0x468,
    ANIM_ACTION_COVER_CROUCH_OUT_LEFT_LOW = 0x469,
    ANIM_ACTION_COVER_CROUCH_OUT_RIGHT_HIGH = 0x46A,
    ANIM_ACTION_COVER_CROUCH_OUT_RIGHT_LOW = 0x46B,
    ANIM_ACTION_COVER_STAND_OUT_LEFT_HIGH = 0x46C,
    ANIM_ACTION_COVER_STAND_OUT_LEFT_LOW = 0x46D,
    ANIM_ACTION_COVER_STAND_OUT_RIGHT_HIGH = 0x46E,
    ANIM_ACTION_COVER_STAND_OUT_RIGHT_LOW = 0x46F,
    ANIM_ACTION_INVESTIGATE_STEP_LEFT = 0x470,
    ANIM_ACTION_INVESTIGATE_STEP_RIGHT = 0x471,
    ANIM_ACTION_SKATE_HOP_TURN = 0x472,
    ANIM_ACTION_SPRINT_SHOVE_LEFT = 0x473,
    ANIM_ACTION_SPRINT_SHOVE_RIGHT = 0x474,
    ANIM_ACTION_SPRINT_SHOVE_LEFT_WEAPON = 0x475,
    ANIM_ACTION_SPRINT_SHOVE_RIGHT_WEAPON = 0x476,
    ANIM_ACTION_SPRINT_SHOVED_LEFT = 0x477,
    ANIM_ACTION_SPRINT_SHOVED_RIGHT = 0x478,
    ANIM_ACTION_SPRINT_SHOVED_LEFT_BACK = 0x479,
    ANIM_ACTION_SPRINT_SHOVED_RIGHT_BACK = 0x47A,
    ANIM_ACTION_WALL_REDIRECT_LEFT = 0x47B,
    ANIM_ACTION_WALL_REDIRECT_RIGHT = 0x47C,
    ANIM_ACTION_SPRINT_TO_WALLSTOP = 0x47D,
    ANIM_ACTION_WALLSTOP_TO_SPRINT_LEFT = 0x47E,
    ANIM_ACTION_WALLSTOP_TO_SPRINT_RIGHT = 0x47F,
    ANIM_ACTION_WALLSTOP_TO_SPRINT_BACK = 0x480,
    ANIM_ACTION_SPRINT_SIEDESTEP_LEFT = 0x481,
    ANIM_ACTION_SPRINT_SIEDESTEP_RIGHT = 0x482,
    ANIM_ACTION_MEDIUM_VAULT = 0x483,
    ANIM_ACTION_MELEE_PUNCH_R1_REACT = 0x484,
    ANIM_ACTION_MELEE_PUNCH_L1_REACT = 0x485,
    ANIM_ACTION_SKYDIVE_TRANS_UPSIDE_DOWN = 0x486,
    ANIM_ACTION_SKYDIVE_TRANS_RIGHTSIDE_UP = 0x487,
    ANIM_ACTION_SKYDIVE_TRANS_DIVE_TO_INVERTED = 0x488,
    ANIM_ACTION_SKYDIVING_REGULAR_RELOAD = 0x489,
    ANIM_ACTION_SKYDIVING_DIVE_RELOAD = 0x48A,
    ANIM_ACTION_SKYDIVING_UPSIDE_DOWN_RELOAD = 0x48B,
    ANIM_ACTION_SKYDIVING_REGULAR_FIRE = 0x48C,
    ANIM_ACTION_SKYDIVING_UPSIDE_DOWN_FIRE = 0x48D,
    ANIM_ACTION_SKYDIVING_PARACHUTE_FIRE = 0x48E,
    ANIM_ACTION_SKYDIVING_PARACHUTE_EXIT = 0x48F,
    ANIM_ACTION_SKYDIVING_PARACHUTE_KILLED = 0x490,
    ANIM_ACTION_SKYDIVING_PARACHUTE_CONVO = 0x491,
    ANIM_ACTION_SKYDIVING_HS_INVERTED_RELEASE = 0x492,
    ANIM_ACTION_SKYDIVING_DEATH = 0x493,
    ANIM_ACTION_SKYDIVING_DEATH_UPSIDE_DOWN = 0x494,
    ANIM_ACTION_SKYDIVING_PLANE_APPROACH = 0x495,
    ANIM_ACTION_PLANE_CABIN_STUMBLE = 0x496,
    ANIM_ACTION_PLANE_STUMBLE_FORWARD = 0x497,
    ANIM_ACTION_PLANE_STUMBLE_BACK = 0x498,
    ANIM_ACTION_PLANE_STUMBLE_LEFT = 0x499,
    ANIM_ACTION_PLANE_STUMBLE_RIGHT = 0x49A,
    ANIM_ACTION_BRUTE_EXCUTE_BACK_FEET = 0x49B,
    ANIM_ACTION_BRUTE_EXCUTE_BACK_HEAD = 0x49C,
    ANIM_ACTION_BRUTE_EXCUTE_BACK_LEFT = 0x49D,
    ANIM_ACTION_BRUTE_EXCUTE_BACK_RIGHT = 0x49E,
    ANIM_ACTION_BRUTE_EXCUTE_FRONT_FEET = 0x49F,
    ANIM_ACTION_BRUTE_EXCUTE_FRONT_HEAD = 0x4A0,
    ANIM_ACTION_BRUTE_EXCUTE_FRONT_LEFT = 0x4A1,
    ANIM_ACTION_BRUTE_EXCUTE_FRONT_RIGHT = 0x4A2,
    ANIM_ACTION_BRUTE_BULLRUSH_FAIL = 0x4A3,
    ANIM_ACTION_BRUTE_BULLRUSH_RECOVER = 0x4A4,
    ANIM_ACTION_ESCORT_TIGER_STUMBLE_RIGHT = 0x4A5,
    ANIM_ACTION_ESCORT_TIGER_STUMBLE_LEFT = 0x4A6,
    ANIM_ACTION_ESCORT_TIGER_SWAT_DRIVER_A = 0x4A7,
    ANIM_ACTION_ESCORT_TIGER_SWAT_DRIVER_B = 0x4A8,
    ANIM_ACTION_ESCORT_PASSENGER_SLAP_TIGER_A = 0x4A9,
    ANIM_ACTION_ESCORT_PASSENGER_SLAP_TIGER_B = 0x4AA,
    ANIM_ACTION_ESCORT_PASSENGER_CALM_TIGER_A = 0x4AB,
    ANIM_ACTION_ESCORT_PASSENGER_CALM_TIGER_B = 0x4AC,
    ANIM_ACTION_ESCORT_PASSENGER_PUNCH_TIGER_A = 0x4AD,
    ANIM_ACTION_ESCORT_PASSENGER_PUNCH_TIGER_B = 0x4AE,
    ANIM_ACTION_ESCORT_DRIVER_NERVOUS_GLANCE = 0x4AF,
    ANIM_ACTION_HAMMER_PREP = 0x4B0,
    ANIM_ACTION_HAMMER_SMASH = 0x4B1,
    ANIM_ACTION_CUST_STAND = 0x4B2,
    ANIM_ACTION_TELEPORT_STOMP_START = 0x4B3,
    ANIM_ACTION_RIDE_KILLBANE_L_PUNCH = 0x4B4,
    ANIM_ACTION_RIDE_KILLBANE_R_PUNCH = 0x4B5,
    ANIM_ACTION_SAINT_FAN_REACT_A = 0x4B6,
    ANIM_ACTION_SAINT_FAN_REACT_B = 0x4B7,
    ANIM_ACTION_SAINT_FAN_REACT_C = 0x4B8,
    ANIM_ACTION_SAINT_FAN_REACT_D = 0x4B9,
    ANIM_ACTION_SAINT_FAN_REACT_E = 0x4BA,
    ANIM_ACTION_SAINT_FAN_REACT_F = 0x4BB,
    ANIM_ACTION_SAINT_FAN_REACT_UPPER_A = 0x4BC,
    ANIM_ACTION_SAINT_FAN_REACT_UPPER_B = 0x4BD,
    ANIM_ACTION_SAINT_FAN_REACT_UPPER_C = 0x4BE,
    ANIM_ACTION_SAINT_FAN_REACT_UPPER_D = 0x4BF,
    ANIM_ACTION_SAINT_FAN_REACT_UPPER_F = 0x4C0,
    ANIM_ACTION_SAINT_PEST_REACT_A = 0x4C1,
    ANIM_ACTION_SAINT_PEST_REACT_B = 0x4C2,
    ANIM_ACTION_SAINT_PEST_REACT_C = 0x4C3,
    ANIM_ACTION_SAINT_PEST_REACT_D = 0x4C4,
    ANIM_ACTION_SAINT_PEST_REACT_MOVING_A = 0x4C5,
    ANIM_ACTION_SAINT_PEST_REACT_MOVING_B = 0x4C6,
    ANIM_ACTION_SAINT_PEST_REACT_MOVING_C = 0x4C7,
    ANIM_ACTION_SAINT_PEST_REACT_MOVING_D = 0x4C8,
    ANIM_ACTION_PRED_COMPUTER_RUN_OPEN = 0x4C9,
    ANIM_ACTION_PRED_COMPUTER_OPEN = 0x4CA,
    ANIM_ACTION_PRED_COMPUTER_CROUCH_OPEN = 0x4CB,
    ANIM_ACTION_PRED_COMPUTER_CLOSE = 0x4CC,
    ANIM_ACTION_PRED_COMPUTER_CROUCH_CLOSE = 0x4CD,
    ANIM_ACTION_FLINCH_CHEST_FRONT_A = 0x4CE,
    ANIM_ACTION_FLINCH_CHEST_FRONT_B = 0x4CF,
    ANIM_ACTION_FLINCH_CHEST_FRONT_C = 0x4D0,
    ANIM_ACTION_FLINCH_CHEST_FRONT_D = 0x4D1,
    ANIM_ACTION_FLINCH_CHEST_FRONT_E = 0x4D2,
    ANIM_ACTION_FLINCH_CHEST_FRONT_F = 0x4D3,
    ANIM_ACTION_FLINCH_CHEST_FRONT_G = 0x4D4,
    ANIM_ACTION_FLINCH_CHEST_FRONT_H = 0x4D5,
    ANIM_ACTION_FLINCH_CHEST_FRONT_I = 0x4D6,
    ANIM_ACTION_FLINCH_CHEST_FRONT_J = 0x4D7,
    ANIM_ACTION_FLINCH_CHEST_FRONT_K = 0x4D8,
    ANIM_ACTION_FLINCH_CHEST_BACK_A = 0x4D9,
    ANIM_ACTION_FLINCH_CHEST_BACK_B = 0x4DA,
    ANIM_ACTION_TAKE_OUT_UMBRELLA = 0x4DB,
    ANIM_ACTION_PUT_AWAY_UMBRELLA = 0x4DC,
    ANIM_ACTION_FIRE_LEFT_A = 0x4DD,
    ANIM_ACTION_FIRE_LEFT_B = 0x4DE,
    ANIM_ACTION_FIRE_LEFT_C = 0x4DF,
    ANIM_ACTION_FIRE_LEFT_D = 0x4E0,
    ANIM_ACTION_FIRE_RIGHT_A = 0x4E1,
    ANIM_ACTION_FIRE_RIGHT_B = 0x4E2,
    ANIM_ACTION_FIRE_RIGHT_C = 0x4E3,
    ANIM_ACTION_FIRE_RIGHT_D = 0x4E4,
    ANIM_ACTION_FIRE_LEFT_B_1 = 0x4E5,
    ANIM_ACTION_FIRE_LEFT_B_2 = 0x4E6,
    ANIM_ACTION_FIRE_LEFT_B_3 = 0x4E7,
    ANIM_ACTION_FIRE_LEFT_B_4 = 0x4E8,
    ANIM_ACTION_FIRE_RIGHT_B_1 = 0x4E9,
    ANIM_ACTION_FIRE_RIGHT_B_2 = 0x4EA,
    ANIM_ACTION_FIRE_RIGHT_B_3 = 0x4EB,
    ANIM_ACTION_FIRE_RIGHT_B_4 = 0x4EC,
    ANIM_ACTION_LEFT_TO_RIGHT = 0x4ED,
    ANIM_ACTION_RIGHT_TO_LEFT = 0x4EE,
    ANIM_ACTION_GUARDIAN_ANGEL_SNIPE = 0x4EF,
    ANIM_ACTION_STAND_TO_FLASHBANG_A = 0x4F0,
    ANIM_ACTION_STAND_TO_FLASHBANG_B = 0x4F1,
    ANIM_ACTION_STAND_TO_FLASHBANG_C = 0x4F2,
    ANIM_ACTION_STAND_TO_FLASHBANG_D = 0x4F3,
    ANIM_ACTION_FLASBANG_A_TO_STAND = 0x4F4,
    ANIM_ACTION_FLASBANG_B_TO_STAND = 0x4F5,
    ANIM_ACTION_FLASBANG_C_TO_STAND = 0x4F6,
    ANIM_ACTION_FLASBANG_D_TO_STAND = 0x4F7,
    ANIM_ACTION_STAND_TO_FIAJ_A = 0x4F8,
    ANIM_ACTION_STAND_TO_FIAJ_B = 0x4F9,
    ANIM_ACTION_STAND_TO_FIAJ_C = 0x4FA,
    ANIM_ACTION_STAND_TO_FIAJ_D = 0x4FB,
    ANIM_ACTION_STAND_TO_FIAJ_E = 0x4FC,
    ANIM_ACTION_STAND_TO_FIAJ_F = 0x4FD,
    ANIM_ACTION_FIAJ_A_TO_STAND = 0x4FE,
    ANIM_ACTION_FIAJ_B_TO_STAND = 0x4FF,
    ANIM_ACTION_FIAJ_C_TO_STAND = 0x500,
    ANIM_ACTION_FIAJ_D_TO_STAND = 0x501,
    ANIM_ACTION_FIAJ_E_TO_STAND = 0x502,
    ANIM_ACTION_FIAJ_F_TO_STAND = 0x503,
    ANIM_ACTION_WOUND_CHEST_STAND_TURN_RIGHT = 0x504,
    ANIM_ACTION_WOUND_CHEST_STAND_TURN_LEFT = 0x505,
    ANIM_ACTION_GA_RELOAD = 0x506,
    ANIM_ACTION_SHARK_ATTACK = 0x507,
    ANIM_ACTION_SHARK_ATTACK_CAR = 0x508,
    ANIM_ACTION_SHARK_ATTACKED = 0x509,
    ANIM_ACTION_CHUMGUN_HIT_BACK_A = 0x50A,
    ANIM_ACTION_CHUMGUN_HIT_BACK_B = 0x50B,
    ANIM_ACTION_CHUMGUN_HIT_BACK_C = 0x50C,
    ANIM_ACTION_CHUMGUN_HIT_FRONT_A = 0x50D,
    ANIM_ACTION_CHUMGUN_HIT_FRONT_B = 0x50E,
    ANIM_ACTION_CHUMGUN_HIT_FRONT_C = 0x50F,
    ANIM_ACTION_QUICKLOOK_BACK_A = 0x510,
    ANIM_ACTION_QUICKLOOK_BACK_B = 0x511,
    ANIM_ACTION_QUICKLOOK_BACK_C = 0x512,
    ANIM_ACTION_QUICKLOOK_FORWARD_A = 0x513,
    ANIM_ACTION_QUICKLOOK_FORWARD_B = 0x514,
    ANIM_ACTION_QUICKLOOK_FORWARD_C = 0x515,
    ANIM_ACTION_QUICKLOOK_LEFT_A = 0x516,
    ANIM_ACTION_QUICKLOOK_LEFT_B = 0x517,
    ANIM_ACTION_QUICKLOOK_RIGHT_A = 0x518,
    ANIM_ACTION_QUICKLOOK_RIGHT_B = 0x519,
    ANIM_ACTION_OHSHIT_BACK_A = 0x51A,
    ANIM_ACTION_OHSHIT_BACK_B = 0x51B,
    ANIM_ACTION_OHSHIT_FORWARD_A = 0x51C,
    ANIM_ACTION_OHSHIT_FORWARD_B = 0x51D,
    ANIM_ACTION_OHSHIT_LEFT_A = 0x51E,
    ANIM_ACTION_OHSHIT_LEFT_B = 0x51F,
    ANIM_ACTION_OHSHIT_RIGHT_A = 0x520,
    ANIM_ACTION_OHSHIT_RIGHT_B = 0x521,
    ANIM_ACTION_CHARGE = 0x522,
    ANIM_ACTION_GENKI_REACTION = 0x523,
    ANIM_ACTION_MINIGUN_START = 0x524,
    ANIM_ACTION_MINIGUN_END = 0x525,
    NUM_ANIMATION_TAGS = 0x526,
};

enum human_team : __int8
{
    HUMAN_TEAM_PLAYERS = 0x0,
    HUMAN_TEAM_LUCHADORES = 0x1,
    HUMAN_TEAM_DECKERS = 0x2,
    HUMAN_TEAM_MORNINGSTAR = 0x3,
    HUMAN_TEAM_NEUTRAL_GANG = 0x4,
    HUMAN_TEAM_POLICE = 0x5,
    HUMAN_TEAM_STAG = 0x6,
    HUMAN_TEAM_CIVILIAN = 0x7,
    NUM_HUMAN_TEAMS = 0x8,
    HUMAN_TEAM_NONE = 0x9,
};

struct human
{
    char _0x00[0x60];
    fl_vector m_pos; 
    fl_matrix m_orient;
    char _0x78[0x7C];

    char _0x110[0xC];
    int hprocessing_flags;
    char _0x120[8];
    character_info* char_info; 
    char _0x130[0xD68];
    character_instance* char_inst;
    char _0xE98[0x1000];
    human_team team;
    int max_hit_points;
    int max_hit_point_bonus;
    int hit_point_bonus_level;
    float hit_points;
    float damage_multiplier;
    float attack_multiplier;
    animation_state anim_state_override;
    animation_state stand_variant;
    animation_state walk_variant;
    animation_state flee_walk_variant;
    animation_state cower_run_variant;
    animation_state cower_stand_variant;
    animation_state observe_variant;
    animation_state run_variant;
    animation_state stand_ready_variant;
    animation_state stand_fire_variant;
    fl_vector m_velocity;
};

struct player : human
{

};

struct aa_dist_info
{
    vm_float m_near_dist;
    float m_fade_in_rate;
    float m_fade_out_rate;
    float m_capsule_inner_multiplier;
    float m_capsule_outer_multiplier;
    bool m_use_cylinder;
};

struct aa_steer_info
{
    float m_steer_x;
    float m_steer_y;
    float m_max_steer_x;
    float m_max_steer_y;
    aa_dist_info m_dist_info;
};

struct aa_slow_info
{
    float m_slow_mult_x;
    float m_slow_mult_y;
    aa_dist_info m_dist_info;
};

struct aa_info
{
    char m_name[32];
    aa_steer_info m_steer_info;
    aa_slow_info m_slow_info;
};

enum cheat_ped_type_override : __int32
{
    CHEAT_PED_TYPE_NONE = 0x0,
    CHEAT_PED_TYPE_ZOMBIE = 0x1,
    CHEAT_PED_TYPE_MASCOT = 0x2,
    CHEAT_PED_TYPE_PIMPS_AND_HOS = 0x3,
};

struct cheat_flags
{
    unsigned __int32 pratfalls : 1;
    unsigned __int32 super_throw : 1;
    unsigned __int32 vehicle_infinite_mass : 1;
    unsigned __int32 vehicle_no_damage : 1;
    unsigned __int32 vehicle_smash : 1;
    unsigned __int32 wrath_of_god : 1;
    unsigned __int32 evil_cars : 1;
    unsigned __int32 evil_cars_2 : 1;
    unsigned __int32 unlimited_ammo : 1;
    unsigned __int32 infinite_sprint : 1;
    unsigned __int32 raining_peds : 1;
    unsigned __int32 ped_war : 1;
    unsigned __int32 drunk_peds : 1;
    unsigned __int32 super_saints : 1;
    unsigned __int32 unlimited_clip : 1;
    unsigned __int32 elevator_to_heaven : 1;
    unsigned __int32 god_mode : 1;
    unsigned __int32 hide_hud : 1;
    unsigned __int32 bloody_mess : 1;
    unsigned __int32 golden_gun : 1;
};

struct cheat_effects
{
    cheat_flags flags;
    float beer_muscles_boost;
    float explosion_boost;
    float human_scale;
    float player_scale[2];
    float jump_height_multiplier;
    fl_vector throw_velocity;
    cheat_ped_type_override ped_type_override;

    static cheat_effects* Singleton()
    {
        return ((cheat_effects*)(ResolveImport() + 0x15FCAD8));
    }
};

struct game_camera
{
    vm_vector ideal_pos; //0x0000
    vm_matrix34 real_orient;
    vm_matrix34 ideal_orient;
    float real_fov;
    float ideal_fov;
   
    static game_camera* Singleton()
    {
        return ((game_camera*)(ResolveImport() + 0x1405B30));
    }
}; //Size: 0x0040

#endif